openapi: 3.0.3
info:
  title: authentik
  version: 2026.2.3
  description: Excerpt of the authentik openapi docs
  contact:
    email: hello@goauthentik.io
  license:
    name: MIT
    url: https://github.com/goauthentik/authentik/blob/main/LICENSE
paths:
  /core/applications/{slug}/used_by/:
    get:
      operationId: core_applications_used_by_list
      description: Get a list of all objects that use this object
      parameters:
      - in: path
        name: slug
        schema:
          type: string
          description: Internal application name, used in URLs.
        required: true
      tags:
      - core
      security:
      - authentik: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsedBy'
          description: ''
  /core/transactional/applications/:
    #keep!
    put:
      operationId: core_transactional_applications_update
      description: Convert data into a blueprint, validate it and apply it
      tags:
      - core
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionApplicationRequest'
        required: true
      security:
      - authentik: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionApplicationResponse'
          description: ''
components:
  schemas:
    ProviderModelEnum:
      enum:
        - authentik_providers_google_workspace.googleworkspaceprovider
        - authentik_providers_ldap.ldapprovider
      type: string

    TransactionApplicationRequest:
      type: object
      description: Serializer for creating a provider and an application in one transaction
      properties:
        provider_model:
          $ref: '#/components/schemas/ProviderModelEnum'
        provider:
          $ref: '#/components/schemas/modelRequest'
      required:
        - app
        - provider
        - provider_model
    TransactionApplicationResponse:
      type: object
      description: Transactional creation response
      properties:
        applied:
          type: boolean
      required:
        - applied

    GoogleWorkspaceProviderRequest:
      type: object
      description: GoogleWorkspaceProvider Serializer
      properties:
        name:
          type: string
          minLength: 1
      required:
        - name
    LDAPProviderRequest:
      type: object
      description: LDAPProvider Serializer
      properties:
        name:
          type: string
          minLength: 1
      required:
        - name
    UsedBy:
      type: object
      description: A list of all objects referencing the queried object
      properties:
        model_name:
          type: string
        pk:
          type: string
        name:
          type: string
      required:
      - model_name
      - name
      - pk
    modelRequest:
      oneOf:
      - $ref: '#/components/schemas/GoogleWorkspaceProviderRequest'
      - $ref: '#/components/schemas/LDAPProviderRequest'
      discriminator:
        propertyName: provider_model
        mapping:
          authentik_providers_google_workspace.googleworkspaceprovider: '#/components/schemas/GoogleWorkspaceProviderRequest'
          authentik_providers_ldap.ldapprovider: '#/components/schemas/LDAPProviderRequest'
  securitySchemes:
    authentik:
      type: http
      scheme: bearer
servers:
- url: /api/v3
