<?php
/**
 * CoreApi
 * PHP version 8.1
 *
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\NextGen\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use AuthentikApi\NextGen\ApiException;
use AuthentikApi\NextGen\Configuration;
use AuthentikApi\NextGen\HeaderSelector;
use AuthentikApi\NextGen\FormDataProcessor;
use AuthentikApi\NextGen\ObjectSerializer;

/**
 * CoreApi Class Doc Comment
 *
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CoreApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'coreApplicationsUsedByList' => [
            'application/json',
        ],
        'coreTransactionalApplicationsUpdate' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation coreApplicationsUsedByList
     *
     * @param  string $slug slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['coreApplicationsUsedByList'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \AuthentikApi\NextGen\Model\UsedBy[]
     */
    public function coreApplicationsUsedByList(
        string $slug,
        string $contentType = self::contentTypes['coreApplicationsUsedByList'][0]
    ): array
    {
        list($response) = $this->coreApplicationsUsedByListWithHttpInfo($slug, $contentType);
        return $response;
    }

    /**
     * Operation coreApplicationsUsedByListWithHttpInfo
     *
     * @param  string $slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['coreApplicationsUsedByList'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \AuthentikApi\NextGen\Model\UsedBy[], HTTP status code, HTTP response headers (array of strings)
     */
    public function coreApplicationsUsedByListWithHttpInfo(
        string $slug,
        string $contentType = self::contentTypes['coreApplicationsUsedByList'][0]
    ): array
    {
        $request = $this->coreApplicationsUsedByListRequest($slug, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\AuthentikApi\NextGen\Model\UsedBy[]',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\AuthentikApi\NextGen\Model\UsedBy[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AuthentikApi\NextGen\Model\UsedBy[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation coreApplicationsUsedByListAsync
     *
     * @param  string $slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['coreApplicationsUsedByList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function coreApplicationsUsedByListAsync(
        string $slug,
        string $contentType = self::contentTypes['coreApplicationsUsedByList'][0]
    ): PromiseInterface
    {
        return $this->coreApplicationsUsedByListAsyncWithHttpInfo($slug, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation coreApplicationsUsedByListAsyncWithHttpInfo
     *
     * @param  string $slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['coreApplicationsUsedByList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function coreApplicationsUsedByListAsyncWithHttpInfo(
        string $slug,
        string $contentType = self::contentTypes['coreApplicationsUsedByList'][0]
    ): PromiseInterface
    {
        $returnType = '\AuthentikApi\NextGen\Model\UsedBy[]';
        $request = $this->coreApplicationsUsedByListRequest($slug, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'coreApplicationsUsedByList'
     *
     * @param  string $slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['coreApplicationsUsedByList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function coreApplicationsUsedByListRequest(
        string $slug,
        string $contentType = self::contentTypes['coreApplicationsUsedByList'][0]
    ): Request
    {

        // verify the required parameter 'slug' is set
        if ($slug === null || (is_array($slug) && count($slug) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $slug when calling coreApplicationsUsedByList'
            );
        }


        $resourcePath = '/core/applications/{slug}/used_by/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($slug !== null) {
            $resourcePath = str_replace(
                '{slug}',
                ObjectSerializer::toPathValue($slug),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation coreTransactionalApplicationsUpdate
     *
     * @param  \AuthentikApi\NextGen\Model\TransactionApplicationRequest $transaction_application_request transaction_application_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['coreTransactionalApplicationsUpdate'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \AuthentikApi\NextGen\Model\TransactionApplicationResponse
     */
    public function coreTransactionalApplicationsUpdate(
        \AuthentikApi\NextGen\Model\TransactionApplicationRequest $transaction_application_request,
        string $contentType = self::contentTypes['coreTransactionalApplicationsUpdate'][0]
    ): \AuthentikApi\NextGen\Model\TransactionApplicationResponse
    {
        list($response) = $this->coreTransactionalApplicationsUpdateWithHttpInfo($transaction_application_request, $contentType);
        return $response;
    }

    /**
     * Operation coreTransactionalApplicationsUpdateWithHttpInfo
     *
     * @param  \AuthentikApi\NextGen\Model\TransactionApplicationRequest $transaction_application_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['coreTransactionalApplicationsUpdate'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \AuthentikApi\NextGen\Model\TransactionApplicationResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function coreTransactionalApplicationsUpdateWithHttpInfo(
        \AuthentikApi\NextGen\Model\TransactionApplicationRequest $transaction_application_request,
        string $contentType = self::contentTypes['coreTransactionalApplicationsUpdate'][0]
    ): array
    {
        $request = $this->coreTransactionalApplicationsUpdateRequest($transaction_application_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\AuthentikApi\NextGen\Model\TransactionApplicationResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\AuthentikApi\NextGen\Model\TransactionApplicationResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AuthentikApi\NextGen\Model\TransactionApplicationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation coreTransactionalApplicationsUpdateAsync
     *
     * @param  \AuthentikApi\NextGen\Model\TransactionApplicationRequest $transaction_application_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['coreTransactionalApplicationsUpdate'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function coreTransactionalApplicationsUpdateAsync(
        \AuthentikApi\NextGen\Model\TransactionApplicationRequest $transaction_application_request,
        string $contentType = self::contentTypes['coreTransactionalApplicationsUpdate'][0]
    ): PromiseInterface
    {
        return $this->coreTransactionalApplicationsUpdateAsyncWithHttpInfo($transaction_application_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation coreTransactionalApplicationsUpdateAsyncWithHttpInfo
     *
     * @param  \AuthentikApi\NextGen\Model\TransactionApplicationRequest $transaction_application_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['coreTransactionalApplicationsUpdate'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function coreTransactionalApplicationsUpdateAsyncWithHttpInfo(
        \AuthentikApi\NextGen\Model\TransactionApplicationRequest $transaction_application_request,
        string $contentType = self::contentTypes['coreTransactionalApplicationsUpdate'][0]
    ): PromiseInterface
    {
        $returnType = '\AuthentikApi\NextGen\Model\TransactionApplicationResponse';
        $request = $this->coreTransactionalApplicationsUpdateRequest($transaction_application_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'coreTransactionalApplicationsUpdate'
     *
     * @param  \AuthentikApi\NextGen\Model\TransactionApplicationRequest $transaction_application_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['coreTransactionalApplicationsUpdate'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function coreTransactionalApplicationsUpdateRequest(
        \AuthentikApi\NextGen\Model\TransactionApplicationRequest $transaction_application_request,
        string $contentType = self::contentTypes['coreTransactionalApplicationsUpdate'][0]
    ): Request
    {

        // verify the required parameter 'transaction_application_request' is set
        if ($transaction_application_request === null || (is_array($transaction_application_request) && count($transaction_application_request) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $transaction_application_request when calling coreTransactionalApplicationsUpdate'
            );
        }


        $resourcePath = '/core/transactional/applications/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($transaction_application_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($transaction_application_request));
            } else {
                $httpBody = $transaction_application_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
