<?php
/**
 * GoogleWorkspaceProviderRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AuthentikApi\Old\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GoogleWorkspaceProviderRequestTest Class Doc Comment
 *
 * @category    Class
 * @description GoogleWorkspaceProvider Serializer
 * @package     AuthentikApi\Old
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GoogleWorkspaceProviderRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GoogleWorkspaceProviderRequest"
     */
    public function testGoogleWorkspaceProviderRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "property_mappings"
     */
    public function testPropertyPropertyMappings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "property_mappings_group"
     */
    public function testPropertyPropertyMappingsGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "delegated_subject"
     */
    public function testPropertyDelegatedSubject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "credentials"
     */
    public function testPropertyCredentials()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "scopes"
     */
    public function testPropertyScopes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "exclude_users_service_account"
     */
    public function testPropertyExcludeUsersServiceAccount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "filter_group"
     */
    public function testPropertyFilterGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "user_delete_action"
     */
    public function testPropertyUserDeleteAction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "group_delete_action"
     */
    public function testPropertyGroupDeleteAction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "default_group_email_domain"
     */
    public function testPropertyDefaultGroupEmailDomain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sync_page_size"
     */
    public function testPropertySyncPageSize()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sync_page_timeout"
     */
    public function testPropertySyncPageTimeout()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dry_run"
     */
    public function testPropertyDryRun()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
