<?php
/**
 * RadiusProviderRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AuthentikApi\Old\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RadiusProviderRequestTest Class Doc Comment
 *
 * @category    Class
 * @description RadiusProvider Serializer
 * @package     AuthentikApi\Old
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RadiusProviderRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RadiusProviderRequest"
     */
    public function testRadiusProviderRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "authentication_flow"
     */
    public function testPropertyAuthenticationFlow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "authorization_flow"
     */
    public function testPropertyAuthorizationFlow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "invalidation_flow"
     */
    public function testPropertyInvalidationFlow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "property_mappings"
     */
    public function testPropertyPropertyMappings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "client_networks"
     */
    public function testPropertyClientNetworks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shared_secret"
     */
    public function testPropertySharedSecret()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mfa_support"
     */
    public function testPropertyMfaSupport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "certificate"
     */
    public function testPropertyCertificate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
