<?php
/**
 * SAMLProviderRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AuthentikApi\Old\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SAMLProviderRequestTest Class Doc Comment
 *
 * @category    Class
 * @description SAMLProvider Serializer
 * @package     AuthentikApi\Old
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SAMLProviderRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SAMLProviderRequest"
     */
    public function testSAMLProviderRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "authentication_flow"
     */
    public function testPropertyAuthenticationFlow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "authorization_flow"
     */
    public function testPropertyAuthorizationFlow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "invalidation_flow"
     */
    public function testPropertyInvalidationFlow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "property_mappings"
     */
    public function testPropertyPropertyMappings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "acs_url"
     */
    public function testPropertyAcsUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sls_url"
     */
    public function testPropertySlsUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "audience"
     */
    public function testPropertyAudience()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "issuer"
     */
    public function testPropertyIssuer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "assertion_valid_not_before"
     */
    public function testPropertyAssertionValidNotBefore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "assertion_valid_not_on_or_after"
     */
    public function testPropertyAssertionValidNotOnOrAfter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "session_valid_not_on_or_after"
     */
    public function testPropertySessionValidNotOnOrAfter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name_id_mapping"
     */
    public function testPropertyNameIdMapping()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "authn_context_class_ref_mapping"
     */
    public function testPropertyAuthnContextClassRefMapping()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "digest_algorithm"
     */
    public function testPropertyDigestAlgorithm()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "signature_algorithm"
     */
    public function testPropertySignatureAlgorithm()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "signing_kp"
     */
    public function testPropertySigningKp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "verification_kp"
     */
    public function testPropertyVerificationKp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "encryption_kp"
     */
    public function testPropertyEncryptionKp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sign_assertion"
     */
    public function testPropertySignAssertion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sign_response"
     */
    public function testPropertySignResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sign_logout_request"
     */
    public function testPropertySignLogoutRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sp_binding"
     */
    public function testPropertySpBinding()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sls_binding"
     */
    public function testPropertySlsBinding()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "logout_method"
     */
    public function testPropertyLogoutMethod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "default_relay_state"
     */
    public function testPropertyDefaultRelayState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "default_name_id_policy"
     */
    public function testPropertyDefaultNameIdPolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
