<?php
/**
 * DigestAlgorithmEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\Old\Model;
use \AuthentikApi\Old\ObjectSerializer;

/**
 * DigestAlgorithmEnum Class Doc Comment
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DigestAlgorithmEnum
{
    /**
     * Possible values of this enum
     */
    public const HTTP___WWW_W3_ORG_2000_09_XMLDSIGSHA1 = 'http://www.w3.org/2000/09/xmldsig#sha1';

    public const HTTP___WWW_W3_ORG_2001_04_XMLENCSHA256 = 'http://www.w3.org/2001/04/xmlenc#sha256';

    public const HTTP___WWW_W3_ORG_2001_04_XMLDSIG_MORESHA384 = 'http://www.w3.org/2001/04/xmldsig-more#sha384';

    public const HTTP___WWW_W3_ORG_2001_04_XMLENCSHA512 = 'http://www.w3.org/2001/04/xmlenc#sha512';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::HTTP___WWW_W3_ORG_2000_09_XMLDSIGSHA1,
            self::HTTP___WWW_W3_ORG_2001_04_XMLENCSHA256,
            self::HTTP___WWW_W3_ORG_2001_04_XMLDSIG_MORESHA384,
            self::HTTP___WWW_W3_ORG_2001_04_XMLENCSHA512
        ];
    }
}


