<?php
/**
 * MicrosoftEntraProviderRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\Old\Model;

use \ArrayAccess;
use \AuthentikApi\Old\ObjectSerializer;

/**
 * MicrosoftEntraProviderRequest Class Doc Comment
 *
 * @category Class
 * @description MicrosoftEntraProvider Serializer
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MicrosoftEntraProviderRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MicrosoftEntraProviderRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'name' => 'string',
        'property_mappings' => 'string[]',
        'property_mappings_group' => 'string[]',
        'client_id' => 'string',
        'client_secret' => 'string',
        'tenant_id' => 'string',
        'exclude_users_service_account' => 'bool',
        'filter_group' => 'string',
        'user_delete_action' => '\AuthentikApi\Old\Model\OutgoingSyncDeleteAction',
        'group_delete_action' => '\AuthentikApi\Old\Model\OutgoingSyncDeleteAction',
        'sync_page_size' => 'int',
        'sync_page_timeout' => 'string',
        'dry_run' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'name' => null,
        'property_mappings' => 'uuid',
        'property_mappings_group' => 'uuid',
        'client_id' => null,
        'client_secret' => null,
        'tenant_id' => null,
        'exclude_users_service_account' => null,
        'filter_group' => 'uuid',
        'user_delete_action' => null,
        'group_delete_action' => null,
        'sync_page_size' => null,
        'sync_page_timeout' => null,
        'dry_run' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'name' => false,
        'property_mappings' => false,
        'property_mappings_group' => false,
        'client_id' => false,
        'client_secret' => false,
        'tenant_id' => false,
        'exclude_users_service_account' => false,
        'filter_group' => true,
        'user_delete_action' => false,
        'group_delete_action' => false,
        'sync_page_size' => false,
        'sync_page_timeout' => false,
        'dry_run' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'property_mappings' => 'property_mappings',
        'property_mappings_group' => 'property_mappings_group',
        'client_id' => 'client_id',
        'client_secret' => 'client_secret',
        'tenant_id' => 'tenant_id',
        'exclude_users_service_account' => 'exclude_users_service_account',
        'filter_group' => 'filter_group',
        'user_delete_action' => 'user_delete_action',
        'group_delete_action' => 'group_delete_action',
        'sync_page_size' => 'sync_page_size',
        'sync_page_timeout' => 'sync_page_timeout',
        'dry_run' => 'dry_run'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'property_mappings' => 'setPropertyMappings',
        'property_mappings_group' => 'setPropertyMappingsGroup',
        'client_id' => 'setClientId',
        'client_secret' => 'setClientSecret',
        'tenant_id' => 'setTenantId',
        'exclude_users_service_account' => 'setExcludeUsersServiceAccount',
        'filter_group' => 'setFilterGroup',
        'user_delete_action' => 'setUserDeleteAction',
        'group_delete_action' => 'setGroupDeleteAction',
        'sync_page_size' => 'setSyncPageSize',
        'sync_page_timeout' => 'setSyncPageTimeout',
        'dry_run' => 'setDryRun'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'property_mappings' => 'getPropertyMappings',
        'property_mappings_group' => 'getPropertyMappingsGroup',
        'client_id' => 'getClientId',
        'client_secret' => 'getClientSecret',
        'tenant_id' => 'getTenantId',
        'exclude_users_service_account' => 'getExcludeUsersServiceAccount',
        'filter_group' => 'getFilterGroup',
        'user_delete_action' => 'getUserDeleteAction',
        'group_delete_action' => 'getGroupDeleteAction',
        'sync_page_size' => 'getSyncPageSize',
        'sync_page_timeout' => 'getSyncPageTimeout',
        'dry_run' => 'getDryRun'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('property_mappings', $data ?? [], null);
        $this->setIfExists('property_mappings_group', $data ?? [], null);
        $this->setIfExists('client_id', $data ?? [], null);
        $this->setIfExists('client_secret', $data ?? [], null);
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('exclude_users_service_account', $data ?? [], null);
        $this->setIfExists('filter_group', $data ?? [], null);
        $this->setIfExists('user_delete_action', $data ?? [], null);
        $this->setIfExists('group_delete_action', $data ?? [], null);
        $this->setIfExists('sync_page_size', $data ?? [], null);
        $this->setIfExists('sync_page_timeout', $data ?? [], null);
        $this->setIfExists('dry_run', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['client_id'] === null) {
            $invalidProperties[] = "'client_id' can't be null";
        }
        if ((mb_strlen($this->container['client_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'client_id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['client_secret'] === null) {
            $invalidProperties[] = "'client_secret' can't be null";
        }
        if ((mb_strlen($this->container['client_secret']) < 1)) {
            $invalidProperties[] = "invalid value for 'client_secret', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['tenant_id'] === null) {
            $invalidProperties[] = "'tenant_id' can't be null";
        }
        if ((mb_strlen($this->container['tenant_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'tenant_id', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['sync_page_size']) && ($this->container['sync_page_size'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'sync_page_size', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['sync_page_size']) && ($this->container['sync_page_size'] < 1)) {
            $invalidProperties[] = "invalid value for 'sync_page_size', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['sync_page_timeout']) && (mb_strlen($this->container['sync_page_timeout']) < 1)) {
            $invalidProperties[] = "invalid value for 'sync_page_timeout', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling MicrosoftEntraProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets property_mappings
     *
     * @return string[]|null
     */
    public function getPropertyMappings()
    {
        return $this->container['property_mappings'];
    }

    /**
     * Sets property_mappings
     *
     * @param string[]|null $property_mappings property_mappings
     *
     * @return self
     */
    public function setPropertyMappings($property_mappings)
    {
        if (is_null($property_mappings)) {
            throw new \InvalidArgumentException('non-nullable property_mappings cannot be null');
        }
        $this->container['property_mappings'] = $property_mappings;

        return $this;
    }

    /**
     * Gets property_mappings_group
     *
     * @return string[]|null
     */
    public function getPropertyMappingsGroup()
    {
        return $this->container['property_mappings_group'];
    }

    /**
     * Sets property_mappings_group
     *
     * @param string[]|null $property_mappings_group Property mappings used for group creation/updating.
     *
     * @return self
     */
    public function setPropertyMappingsGroup($property_mappings_group)
    {
        if (is_null($property_mappings_group)) {
            throw new \InvalidArgumentException('non-nullable property_mappings_group cannot be null');
        }
        $this->container['property_mappings_group'] = $property_mappings_group;

        return $this;
    }

    /**
     * Gets client_id
     *
     * @return string
     */
    public function getClientId()
    {
        return $this->container['client_id'];
    }

    /**
     * Sets client_id
     *
     * @param string $client_id client_id
     *
     * @return self
     */
    public function setClientId($client_id)
    {
        if (is_null($client_id)) {
            throw new \InvalidArgumentException('non-nullable client_id cannot be null');
        }

        if ((mb_strlen($client_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $client_id when calling MicrosoftEntraProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['client_id'] = $client_id;

        return $this;
    }

    /**
     * Gets client_secret
     *
     * @return string
     */
    public function getClientSecret()
    {
        return $this->container['client_secret'];
    }

    /**
     * Sets client_secret
     *
     * @param string $client_secret client_secret
     *
     * @return self
     */
    public function setClientSecret($client_secret)
    {
        if (is_null($client_secret)) {
            throw new \InvalidArgumentException('non-nullable client_secret cannot be null');
        }

        if ((mb_strlen($client_secret) < 1)) {
            throw new \InvalidArgumentException('invalid length for $client_secret when calling MicrosoftEntraProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['client_secret'] = $client_secret;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return string
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param string $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }

        if ((mb_strlen($tenant_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $tenant_id when calling MicrosoftEntraProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets exclude_users_service_account
     *
     * @return bool|null
     */
    public function getExcludeUsersServiceAccount()
    {
        return $this->container['exclude_users_service_account'];
    }

    /**
     * Sets exclude_users_service_account
     *
     * @param bool|null $exclude_users_service_account exclude_users_service_account
     *
     * @return self
     */
    public function setExcludeUsersServiceAccount($exclude_users_service_account)
    {
        if (is_null($exclude_users_service_account)) {
            throw new \InvalidArgumentException('non-nullable exclude_users_service_account cannot be null');
        }
        $this->container['exclude_users_service_account'] = $exclude_users_service_account;

        return $this;
    }

    /**
     * Gets filter_group
     *
     * @return string|null
     */
    public function getFilterGroup()
    {
        return $this->container['filter_group'];
    }

    /**
     * Sets filter_group
     *
     * @param string|null $filter_group filter_group
     *
     * @return self
     */
    public function setFilterGroup($filter_group)
    {
        if (is_null($filter_group)) {
            array_push($this->openAPINullablesSetToNull, 'filter_group');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('filter_group', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['filter_group'] = $filter_group;

        return $this;
    }

    /**
     * Gets user_delete_action
     *
     * @return \AuthentikApi\Old\Model\OutgoingSyncDeleteAction|null
     */
    public function getUserDeleteAction()
    {
        return $this->container['user_delete_action'];
    }

    /**
     * Sets user_delete_action
     *
     * @param \AuthentikApi\Old\Model\OutgoingSyncDeleteAction|null $user_delete_action user_delete_action
     *
     * @return self
     */
    public function setUserDeleteAction($user_delete_action)
    {
        if (is_null($user_delete_action)) {
            throw new \InvalidArgumentException('non-nullable user_delete_action cannot be null');
        }
        $this->container['user_delete_action'] = $user_delete_action;

        return $this;
    }

    /**
     * Gets group_delete_action
     *
     * @return \AuthentikApi\Old\Model\OutgoingSyncDeleteAction|null
     */
    public function getGroupDeleteAction()
    {
        return $this->container['group_delete_action'];
    }

    /**
     * Sets group_delete_action
     *
     * @param \AuthentikApi\Old\Model\OutgoingSyncDeleteAction|null $group_delete_action group_delete_action
     *
     * @return self
     */
    public function setGroupDeleteAction($group_delete_action)
    {
        if (is_null($group_delete_action)) {
            throw new \InvalidArgumentException('non-nullable group_delete_action cannot be null');
        }
        $this->container['group_delete_action'] = $group_delete_action;

        return $this;
    }

    /**
     * Gets sync_page_size
     *
     * @return int|null
     */
    public function getSyncPageSize()
    {
        return $this->container['sync_page_size'];
    }

    /**
     * Sets sync_page_size
     *
     * @param int|null $sync_page_size Controls the number of objects synced in a single task
     *
     * @return self
     */
    public function setSyncPageSize($sync_page_size)
    {
        if (is_null($sync_page_size)) {
            throw new \InvalidArgumentException('non-nullable sync_page_size cannot be null');
        }

        if (($sync_page_size > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $sync_page_size when calling MicrosoftEntraProviderRequest., must be smaller than or equal to 2147483647.');
        }
        if (($sync_page_size < 1)) {
            throw new \InvalidArgumentException('invalid value for $sync_page_size when calling MicrosoftEntraProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['sync_page_size'] = $sync_page_size;

        return $this;
    }

    /**
     * Gets sync_page_timeout
     *
     * @return string|null
     */
    public function getSyncPageTimeout()
    {
        return $this->container['sync_page_timeout'];
    }

    /**
     * Sets sync_page_timeout
     *
     * @param string|null $sync_page_timeout Timeout for synchronization of a single page
     *
     * @return self
     */
    public function setSyncPageTimeout($sync_page_timeout)
    {
        if (is_null($sync_page_timeout)) {
            throw new \InvalidArgumentException('non-nullable sync_page_timeout cannot be null');
        }

        if ((mb_strlen($sync_page_timeout) < 1)) {
            throw new \InvalidArgumentException('invalid length for $sync_page_timeout when calling MicrosoftEntraProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['sync_page_timeout'] = $sync_page_timeout;

        return $this;
    }

    /**
     * Gets dry_run
     *
     * @return bool|null
     */
    public function getDryRun()
    {
        return $this->container['dry_run'];
    }

    /**
     * Sets dry_run
     *
     * @param bool|null $dry_run When enabled, provider will not modify or create objects in the remote system.
     *
     * @return self
     */
    public function setDryRun($dry_run)
    {
        if (is_null($dry_run)) {
            throw new \InvalidArgumentException('non-nullable dry_run cannot be null');
        }
        $this->container['dry_run'] = $dry_run;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


