<?php
/**
 * ProviderModelEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\Old\Model;
use \AuthentikApi\Old\ObjectSerializer;

/**
 * ProviderModelEnum Class Doc Comment
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProviderModelEnum
{
    /**
     * Possible values of this enum
     */
    public const AUTHENTIK_PROVIDERS_GOOGLE_WORKSPACE_GOOGLEWORKSPACEPROVIDER = 'authentik_providers_google_workspace.googleworkspaceprovider';

    public const AUTHENTIK_PROVIDERS_LDAP_LDAPPROVIDER = 'authentik_providers_ldap.ldapprovider';

    public const AUTHENTIK_PROVIDERS_MICROSOFT_ENTRA_MICROSOFTENTRAPROVIDER = 'authentik_providers_microsoft_entra.microsoftentraprovider';

    public const AUTHENTIK_PROVIDERS_OAUTH2_OAUTH2PROVIDER = 'authentik_providers_oauth2.oauth2provider';

    public const AUTHENTIK_PROVIDERS_PROXY_PROXYPROVIDER = 'authentik_providers_proxy.proxyprovider';

    public const AUTHENTIK_PROVIDERS_RAC_RACPROVIDER = 'authentik_providers_rac.racprovider';

    public const AUTHENTIK_PROVIDERS_RADIUS_RADIUSPROVIDER = 'authentik_providers_radius.radiusprovider';

    public const AUTHENTIK_PROVIDERS_SAML_SAMLPROVIDER = 'authentik_providers_saml.samlprovider';

    public const AUTHENTIK_PROVIDERS_SCIM_SCIMPROVIDER = 'authentik_providers_scim.scimprovider';

    public const AUTHENTIK_PROVIDERS_SSF_SSFPROVIDER = 'authentik_providers_ssf.ssfprovider';

    public const AUTHENTIK_PROVIDERS_WS_FEDERATION_WSFEDERATIONPROVIDER = 'authentik_providers_ws_federation.wsfederationprovider';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AUTHENTIK_PROVIDERS_GOOGLE_WORKSPACE_GOOGLEWORKSPACEPROVIDER,
            self::AUTHENTIK_PROVIDERS_LDAP_LDAPPROVIDER,
            self::AUTHENTIK_PROVIDERS_MICROSOFT_ENTRA_MICROSOFTENTRAPROVIDER,
            self::AUTHENTIK_PROVIDERS_OAUTH2_OAUTH2PROVIDER,
            self::AUTHENTIK_PROVIDERS_PROXY_PROXYPROVIDER,
            self::AUTHENTIK_PROVIDERS_RAC_RACPROVIDER,
            self::AUTHENTIK_PROVIDERS_RADIUS_RADIUSPROVIDER,
            self::AUTHENTIK_PROVIDERS_SAML_SAMLPROVIDER,
            self::AUTHENTIK_PROVIDERS_SCIM_SCIMPROVIDER,
            self::AUTHENTIK_PROVIDERS_SSF_SSFPROVIDER,
            self::AUTHENTIK_PROVIDERS_WS_FEDERATION_WSFEDERATIONPROVIDER
        ];
    }
}


