<?php
/**
 * ProviderModelEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\Old\Model;
use \AuthentikApi\Old\ObjectSerializer;

/**
 * ProviderModelEnum Class Doc Comment
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProviderModelEnum
{
    /**
     * Possible values of this enum
     */
    public const AUTHENTIK_PROVIDERS_GOOGLE_WORKSPACE_GOOGLEWORKSPACEPROVIDER = 'authentik_providers_google_workspace.googleworkspaceprovider';

    public const AUTHENTIK_PROVIDERS_LDAP_LDAPPROVIDER = 'authentik_providers_ldap.ldapprovider';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AUTHENTIK_PROVIDERS_GOOGLE_WORKSPACE_GOOGLEWORKSPACEPROVIDER,
            self::AUTHENTIK_PROVIDERS_LDAP_LDAPPROVIDER
        ];
    }
}


