<?php
/**
 * RACProviderRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\Old\Model;

use \ArrayAccess;
use \AuthentikApi\Old\ObjectSerializer;

/**
 * RACProviderRequest Class Doc Comment
 *
 * @category Class
 * @description RACProvider Serializer
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RACProviderRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'RACProviderRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'name' => 'string',
        'authentication_flow' => 'string',
        'authorization_flow' => 'string',
        'property_mappings' => 'string[]',
        'settings' => 'array<string,mixed>',
        'connection_expiry' => 'string',
        'delete_token_on_disconnect' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'name' => null,
        'authentication_flow' => 'uuid',
        'authorization_flow' => 'uuid',
        'property_mappings' => 'uuid',
        'settings' => null,
        'connection_expiry' => null,
        'delete_token_on_disconnect' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'name' => false,
        'authentication_flow' => true,
        'authorization_flow' => false,
        'property_mappings' => false,
        'settings' => false,
        'connection_expiry' => false,
        'delete_token_on_disconnect' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'authentication_flow' => 'authentication_flow',
        'authorization_flow' => 'authorization_flow',
        'property_mappings' => 'property_mappings',
        'settings' => 'settings',
        'connection_expiry' => 'connection_expiry',
        'delete_token_on_disconnect' => 'delete_token_on_disconnect'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'authentication_flow' => 'setAuthenticationFlow',
        'authorization_flow' => 'setAuthorizationFlow',
        'property_mappings' => 'setPropertyMappings',
        'settings' => 'setSettings',
        'connection_expiry' => 'setConnectionExpiry',
        'delete_token_on_disconnect' => 'setDeleteTokenOnDisconnect'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'authentication_flow' => 'getAuthenticationFlow',
        'authorization_flow' => 'getAuthorizationFlow',
        'property_mappings' => 'getPropertyMappings',
        'settings' => 'getSettings',
        'connection_expiry' => 'getConnectionExpiry',
        'delete_token_on_disconnect' => 'getDeleteTokenOnDisconnect'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('authentication_flow', $data ?? [], null);
        $this->setIfExists('authorization_flow', $data ?? [], null);
        $this->setIfExists('property_mappings', $data ?? [], null);
        $this->setIfExists('settings', $data ?? [], null);
        $this->setIfExists('connection_expiry', $data ?? [], null);
        $this->setIfExists('delete_token_on_disconnect', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['authorization_flow'] === null) {
            $invalidProperties[] = "'authorization_flow' can't be null";
        }
        if (!is_null($this->container['connection_expiry']) && (mb_strlen($this->container['connection_expiry']) < 1)) {
            $invalidProperties[] = "invalid value for 'connection_expiry', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling RACProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets authentication_flow
     *
     * @return string|null
     */
    public function getAuthenticationFlow()
    {
        return $this->container['authentication_flow'];
    }

    /**
     * Sets authentication_flow
     *
     * @param string|null $authentication_flow Flow used for authentication when the associated application is accessed by an un-authenticated user.
     *
     * @return self
     */
    public function setAuthenticationFlow($authentication_flow)
    {
        if (is_null($authentication_flow)) {
            array_push($this->openAPINullablesSetToNull, 'authentication_flow');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authentication_flow', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authentication_flow'] = $authentication_flow;

        return $this;
    }

    /**
     * Gets authorization_flow
     *
     * @return string
     */
    public function getAuthorizationFlow()
    {
        return $this->container['authorization_flow'];
    }

    /**
     * Sets authorization_flow
     *
     * @param string $authorization_flow Flow used when authorizing this provider.
     *
     * @return self
     */
    public function setAuthorizationFlow($authorization_flow)
    {
        if (is_null($authorization_flow)) {
            throw new \InvalidArgumentException('non-nullable authorization_flow cannot be null');
        }
        $this->container['authorization_flow'] = $authorization_flow;

        return $this;
    }

    /**
     * Gets property_mappings
     *
     * @return string[]|null
     */
    public function getPropertyMappings()
    {
        return $this->container['property_mappings'];
    }

    /**
     * Sets property_mappings
     *
     * @param string[]|null $property_mappings property_mappings
     *
     * @return self
     */
    public function setPropertyMappings($property_mappings)
    {
        if (is_null($property_mappings)) {
            throw new \InvalidArgumentException('non-nullable property_mappings cannot be null');
        }
        $this->container['property_mappings'] = $property_mappings;

        return $this;
    }

    /**
     * Gets settings
     *
     * @return array<string,mixed>|null
     */
    public function getSettings()
    {
        return $this->container['settings'];
    }

    /**
     * Sets settings
     *
     * @param array<string,mixed>|null $settings settings
     *
     * @return self
     */
    public function setSettings($settings)
    {
        if (is_null($settings)) {
            throw new \InvalidArgumentException('non-nullable settings cannot be null');
        }
        $this->container['settings'] = $settings;

        return $this;
    }

    /**
     * Gets connection_expiry
     *
     * @return string|null
     */
    public function getConnectionExpiry()
    {
        return $this->container['connection_expiry'];
    }

    /**
     * Sets connection_expiry
     *
     * @param string|null $connection_expiry Determines how long a session lasts. Default of 0 means that the sessions lasts until the browser is closed. (Format: hours=-1;minutes=-2;seconds=-3)
     *
     * @return self
     */
    public function setConnectionExpiry($connection_expiry)
    {
        if (is_null($connection_expiry)) {
            throw new \InvalidArgumentException('non-nullable connection_expiry cannot be null');
        }

        if ((mb_strlen($connection_expiry) < 1)) {
            throw new \InvalidArgumentException('invalid length for $connection_expiry when calling RACProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['connection_expiry'] = $connection_expiry;

        return $this;
    }

    /**
     * Gets delete_token_on_disconnect
     *
     * @return bool|null
     */
    public function getDeleteTokenOnDisconnect()
    {
        return $this->container['delete_token_on_disconnect'];
    }

    /**
     * Sets delete_token_on_disconnect
     *
     * @param bool|null $delete_token_on_disconnect When set to true, connection tokens will be deleted upon disconnect.
     *
     * @return self
     */
    public function setDeleteTokenOnDisconnect($delete_token_on_disconnect)
    {
        if (is_null($delete_token_on_disconnect)) {
            throw new \InvalidArgumentException('non-nullable delete_token_on_disconnect cannot be null');
        }
        $this->container['delete_token_on_disconnect'] = $delete_token_on_disconnect;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


