<?php
/**
 * SCIMProviderRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\Old\Model;

use \ArrayAccess;
use \AuthentikApi\Old\ObjectSerializer;

/**
 * SCIMProviderRequest Class Doc Comment
 *
 * @category Class
 * @description SCIMProvider Serializer
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SCIMProviderRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'SCIMProviderRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'name' => 'string',
        'property_mappings' => 'string[]',
        'property_mappings_group' => 'string[]',
        'url' => 'string',
        'verify_certificates' => 'bool',
        'token' => 'string',
        'auth_mode' => '\AuthentikApi\Old\Model\SCIMAuthenticationModeEnum',
        'auth_oauth' => 'string',
        'auth_oauth_params' => 'array<string,mixed>',
        'compatibility_mode' => '\AuthentikApi\Old\Model\CompatibilityModeEnum',
        'service_provider_config_cache_timeout' => 'string',
        'exclude_users_service_account' => 'bool',
        'sync_page_size' => 'int',
        'sync_page_timeout' => 'string',
        'group_filters' => 'string[]',
        'dry_run' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'name' => null,
        'property_mappings' => 'uuid',
        'property_mappings_group' => 'uuid',
        'url' => null,
        'verify_certificates' => null,
        'token' => null,
        'auth_mode' => null,
        'auth_oauth' => 'uuid',
        'auth_oauth_params' => null,
        'compatibility_mode' => null,
        'service_provider_config_cache_timeout' => null,
        'exclude_users_service_account' => null,
        'sync_page_size' => null,
        'sync_page_timeout' => null,
        'group_filters' => 'uuid',
        'dry_run' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'name' => false,
        'property_mappings' => false,
        'property_mappings_group' => false,
        'url' => false,
        'verify_certificates' => false,
        'token' => false,
        'auth_mode' => false,
        'auth_oauth' => true,
        'auth_oauth_params' => false,
        'compatibility_mode' => false,
        'service_provider_config_cache_timeout' => false,
        'exclude_users_service_account' => false,
        'sync_page_size' => false,
        'sync_page_timeout' => false,
        'group_filters' => false,
        'dry_run' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'property_mappings' => 'property_mappings',
        'property_mappings_group' => 'property_mappings_group',
        'url' => 'url',
        'verify_certificates' => 'verify_certificates',
        'token' => 'token',
        'auth_mode' => 'auth_mode',
        'auth_oauth' => 'auth_oauth',
        'auth_oauth_params' => 'auth_oauth_params',
        'compatibility_mode' => 'compatibility_mode',
        'service_provider_config_cache_timeout' => 'service_provider_config_cache_timeout',
        'exclude_users_service_account' => 'exclude_users_service_account',
        'sync_page_size' => 'sync_page_size',
        'sync_page_timeout' => 'sync_page_timeout',
        'group_filters' => 'group_filters',
        'dry_run' => 'dry_run'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'property_mappings' => 'setPropertyMappings',
        'property_mappings_group' => 'setPropertyMappingsGroup',
        'url' => 'setUrl',
        'verify_certificates' => 'setVerifyCertificates',
        'token' => 'setToken',
        'auth_mode' => 'setAuthMode',
        'auth_oauth' => 'setAuthOauth',
        'auth_oauth_params' => 'setAuthOauthParams',
        'compatibility_mode' => 'setCompatibilityMode',
        'service_provider_config_cache_timeout' => 'setServiceProviderConfigCacheTimeout',
        'exclude_users_service_account' => 'setExcludeUsersServiceAccount',
        'sync_page_size' => 'setSyncPageSize',
        'sync_page_timeout' => 'setSyncPageTimeout',
        'group_filters' => 'setGroupFilters',
        'dry_run' => 'setDryRun'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'property_mappings' => 'getPropertyMappings',
        'property_mappings_group' => 'getPropertyMappingsGroup',
        'url' => 'getUrl',
        'verify_certificates' => 'getVerifyCertificates',
        'token' => 'getToken',
        'auth_mode' => 'getAuthMode',
        'auth_oauth' => 'getAuthOauth',
        'auth_oauth_params' => 'getAuthOauthParams',
        'compatibility_mode' => 'getCompatibilityMode',
        'service_provider_config_cache_timeout' => 'getServiceProviderConfigCacheTimeout',
        'exclude_users_service_account' => 'getExcludeUsersServiceAccount',
        'sync_page_size' => 'getSyncPageSize',
        'sync_page_timeout' => 'getSyncPageTimeout',
        'group_filters' => 'getGroupFilters',
        'dry_run' => 'getDryRun'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('property_mappings', $data ?? [], null);
        $this->setIfExists('property_mappings_group', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('verify_certificates', $data ?? [], null);
        $this->setIfExists('token', $data ?? [], null);
        $this->setIfExists('auth_mode', $data ?? [], null);
        $this->setIfExists('auth_oauth', $data ?? [], null);
        $this->setIfExists('auth_oauth_params', $data ?? [], null);
        $this->setIfExists('compatibility_mode', $data ?? [], null);
        $this->setIfExists('service_provider_config_cache_timeout', $data ?? [], null);
        $this->setIfExists('exclude_users_service_account', $data ?? [], null);
        $this->setIfExists('sync_page_size', $data ?? [], null);
        $this->setIfExists('sync_page_timeout', $data ?? [], null);
        $this->setIfExists('group_filters', $data ?? [], null);
        $this->setIfExists('dry_run', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ((mb_strlen($this->container['url']) < 1)) {
            $invalidProperties[] = "invalid value for 'url', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['service_provider_config_cache_timeout']) && (mb_strlen($this->container['service_provider_config_cache_timeout']) < 1)) {
            $invalidProperties[] = "invalid value for 'service_provider_config_cache_timeout', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['sync_page_size']) && ($this->container['sync_page_size'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'sync_page_size', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['sync_page_size']) && ($this->container['sync_page_size'] < 1)) {
            $invalidProperties[] = "invalid value for 'sync_page_size', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['sync_page_timeout']) && (mb_strlen($this->container['sync_page_timeout']) < 1)) {
            $invalidProperties[] = "invalid value for 'sync_page_timeout', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling SCIMProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets property_mappings
     *
     * @return string[]|null
     */
    public function getPropertyMappings()
    {
        return $this->container['property_mappings'];
    }

    /**
     * Sets property_mappings
     *
     * @param string[]|null $property_mappings property_mappings
     *
     * @return self
     */
    public function setPropertyMappings($property_mappings)
    {
        if (is_null($property_mappings)) {
            throw new \InvalidArgumentException('non-nullable property_mappings cannot be null');
        }
        $this->container['property_mappings'] = $property_mappings;

        return $this;
    }

    /**
     * Gets property_mappings_group
     *
     * @return string[]|null
     */
    public function getPropertyMappingsGroup()
    {
        return $this->container['property_mappings_group'];
    }

    /**
     * Sets property_mappings_group
     *
     * @param string[]|null $property_mappings_group Property mappings used for group creation/updating.
     *
     * @return self
     */
    public function setPropertyMappingsGroup($property_mappings_group)
    {
        if (is_null($property_mappings_group)) {
            throw new \InvalidArgumentException('non-nullable property_mappings_group cannot be null');
        }
        $this->container['property_mappings_group'] = $property_mappings_group;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url Base URL to SCIM requests, usually ends in /v2
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }

        if ((mb_strlen($url) < 1)) {
            throw new \InvalidArgumentException('invalid length for $url when calling SCIMProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets verify_certificates
     *
     * @return bool|null
     */
    public function getVerifyCertificates()
    {
        return $this->container['verify_certificates'];
    }

    /**
     * Sets verify_certificates
     *
     * @param bool|null $verify_certificates verify_certificates
     *
     * @return self
     */
    public function setVerifyCertificates($verify_certificates)
    {
        if (is_null($verify_certificates)) {
            throw new \InvalidArgumentException('non-nullable verify_certificates cannot be null');
        }
        $this->container['verify_certificates'] = $verify_certificates;

        return $this;
    }

    /**
     * Gets token
     *
     * @return string|null
     */
    public function getToken()
    {
        return $this->container['token'];
    }

    /**
     * Sets token
     *
     * @param string|null $token Authentication token
     *
     * @return self
     */
    public function setToken($token)
    {
        if (is_null($token)) {
            throw new \InvalidArgumentException('non-nullable token cannot be null');
        }
        $this->container['token'] = $token;

        return $this;
    }

    /**
     * Gets auth_mode
     *
     * @return \AuthentikApi\Old\Model\SCIMAuthenticationModeEnum|null
     */
    public function getAuthMode()
    {
        return $this->container['auth_mode'];
    }

    /**
     * Sets auth_mode
     *
     * @param \AuthentikApi\Old\Model\SCIMAuthenticationModeEnum|null $auth_mode auth_mode
     *
     * @return self
     */
    public function setAuthMode($auth_mode)
    {
        if (is_null($auth_mode)) {
            throw new \InvalidArgumentException('non-nullable auth_mode cannot be null');
        }
        $this->container['auth_mode'] = $auth_mode;

        return $this;
    }

    /**
     * Gets auth_oauth
     *
     * @return string|null
     */
    public function getAuthOauth()
    {
        return $this->container['auth_oauth'];
    }

    /**
     * Sets auth_oauth
     *
     * @param string|null $auth_oauth OAuth Source used for authentication
     *
     * @return self
     */
    public function setAuthOauth($auth_oauth)
    {
        if (is_null($auth_oauth)) {
            array_push($this->openAPINullablesSetToNull, 'auth_oauth');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auth_oauth', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auth_oauth'] = $auth_oauth;

        return $this;
    }

    /**
     * Gets auth_oauth_params
     *
     * @return array<string,mixed>|null
     */
    public function getAuthOauthParams()
    {
        return $this->container['auth_oauth_params'];
    }

    /**
     * Sets auth_oauth_params
     *
     * @param array<string,mixed>|null $auth_oauth_params Additional OAuth parameters, such as grant_type
     *
     * @return self
     */
    public function setAuthOauthParams($auth_oauth_params)
    {
        if (is_null($auth_oauth_params)) {
            throw new \InvalidArgumentException('non-nullable auth_oauth_params cannot be null');
        }
        $this->container['auth_oauth_params'] = $auth_oauth_params;

        return $this;
    }

    /**
     * Gets compatibility_mode
     *
     * @return \AuthentikApi\Old\Model\CompatibilityModeEnum|null
     */
    public function getCompatibilityMode()
    {
        return $this->container['compatibility_mode'];
    }

    /**
     * Sets compatibility_mode
     *
     * @param \AuthentikApi\Old\Model\CompatibilityModeEnum|null $compatibility_mode Alter authentik behavior for vendor-specific SCIM implementations.
     *
     * @return self
     */
    public function setCompatibilityMode($compatibility_mode)
    {
        if (is_null($compatibility_mode)) {
            throw new \InvalidArgumentException('non-nullable compatibility_mode cannot be null');
        }
        $this->container['compatibility_mode'] = $compatibility_mode;

        return $this;
    }

    /**
     * Gets service_provider_config_cache_timeout
     *
     * @return string|null
     */
    public function getServiceProviderConfigCacheTimeout()
    {
        return $this->container['service_provider_config_cache_timeout'];
    }

    /**
     * Sets service_provider_config_cache_timeout
     *
     * @param string|null $service_provider_config_cache_timeout Cache duration for ServiceProviderConfig responses. Set minutes=0 to disable.
     *
     * @return self
     */
    public function setServiceProviderConfigCacheTimeout($service_provider_config_cache_timeout)
    {
        if (is_null($service_provider_config_cache_timeout)) {
            throw new \InvalidArgumentException('non-nullable service_provider_config_cache_timeout cannot be null');
        }

        if ((mb_strlen($service_provider_config_cache_timeout) < 1)) {
            throw new \InvalidArgumentException('invalid length for $service_provider_config_cache_timeout when calling SCIMProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['service_provider_config_cache_timeout'] = $service_provider_config_cache_timeout;

        return $this;
    }

    /**
     * Gets exclude_users_service_account
     *
     * @return bool|null
     */
    public function getExcludeUsersServiceAccount()
    {
        return $this->container['exclude_users_service_account'];
    }

    /**
     * Sets exclude_users_service_account
     *
     * @param bool|null $exclude_users_service_account exclude_users_service_account
     *
     * @return self
     */
    public function setExcludeUsersServiceAccount($exclude_users_service_account)
    {
        if (is_null($exclude_users_service_account)) {
            throw new \InvalidArgumentException('non-nullable exclude_users_service_account cannot be null');
        }
        $this->container['exclude_users_service_account'] = $exclude_users_service_account;

        return $this;
    }

    /**
     * Gets sync_page_size
     *
     * @return int|null
     */
    public function getSyncPageSize()
    {
        return $this->container['sync_page_size'];
    }

    /**
     * Sets sync_page_size
     *
     * @param int|null $sync_page_size Controls the number of objects synced in a single task
     *
     * @return self
     */
    public function setSyncPageSize($sync_page_size)
    {
        if (is_null($sync_page_size)) {
            throw new \InvalidArgumentException('non-nullable sync_page_size cannot be null');
        }

        if (($sync_page_size > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $sync_page_size when calling SCIMProviderRequest., must be smaller than or equal to 2147483647.');
        }
        if (($sync_page_size < 1)) {
            throw new \InvalidArgumentException('invalid value for $sync_page_size when calling SCIMProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['sync_page_size'] = $sync_page_size;

        return $this;
    }

    /**
     * Gets sync_page_timeout
     *
     * @return string|null
     */
    public function getSyncPageTimeout()
    {
        return $this->container['sync_page_timeout'];
    }

    /**
     * Sets sync_page_timeout
     *
     * @param string|null $sync_page_timeout Timeout for synchronization of a single page
     *
     * @return self
     */
    public function setSyncPageTimeout($sync_page_timeout)
    {
        if (is_null($sync_page_timeout)) {
            throw new \InvalidArgumentException('non-nullable sync_page_timeout cannot be null');
        }

        if ((mb_strlen($sync_page_timeout) < 1)) {
            throw new \InvalidArgumentException('invalid length for $sync_page_timeout when calling SCIMProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['sync_page_timeout'] = $sync_page_timeout;

        return $this;
    }

    /**
     * Gets group_filters
     *
     * @return string[]|null
     */
    public function getGroupFilters()
    {
        return $this->container['group_filters'];
    }

    /**
     * Sets group_filters
     *
     * @param string[]|null $group_filters Group filters used to define sync-scope for groups.
     *
     * @return self
     */
    public function setGroupFilters($group_filters)
    {
        if (is_null($group_filters)) {
            throw new \InvalidArgumentException('non-nullable group_filters cannot be null');
        }
        $this->container['group_filters'] = $group_filters;

        return $this;
    }

    /**
     * Gets dry_run
     *
     * @return bool|null
     */
    public function getDryRun()
    {
        return $this->container['dry_run'];
    }

    /**
     * Sets dry_run
     *
     * @param bool|null $dry_run When enabled, provider will not modify or create objects in the remote system.
     *
     * @return self
     */
    public function setDryRun($dry_run)
    {
        if (is_null($dry_run)) {
            throw new \InvalidArgumentException('non-nullable dry_run cannot be null');
        }
        $this->container['dry_run'] = $dry_run;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


