<?php
/**
 * SubModeEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\Old\Model;
use \AuthentikApi\Old\ObjectSerializer;

/**
 * SubModeEnum Class Doc Comment
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SubModeEnum
{
    /**
     * Possible values of this enum
     */
    public const HASHED_USER_ID = 'hashed_user_id';

    public const USER_ID = 'user_id';

    public const USER_UUID = 'user_uuid';

    public const USER_USERNAME = 'user_username';

    public const USER_EMAIL = 'user_email';

    public const USER_UPN = 'user_upn';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::HASHED_USER_ID,
            self::USER_ID,
            self::USER_UUID,
            self::USER_USERNAME,
            self::USER_EMAIL,
            self::USER_UPN
        ];
    }
}


