<?php
/**
 * UsedByActionEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\Old\Model;
use \AuthentikApi\Old\ObjectSerializer;

/**
 * UsedByActionEnum Class Doc Comment
 *
 * @category Class
 * @package  AuthentikApi\Old
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UsedByActionEnum
{
    /**
     * Possible values of this enum
     */
    public const CASCADE = 'cascade';

    public const CASCADE_MANY = 'cascade_many';

    public const SET_NULL = 'set_null';

    public const SET_DEFAULT = 'set_default';

    public const LEFT_DANGLING = 'left_dangling';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CASCADE,
            self::CASCADE_MANY,
            self::SET_NULL,
            self::SET_DEFAULT,
            self::LEFT_DANGLING
        ];
    }
}


