<?php
/**
 * ApplicationRequest
 *
 * PHP version 8.1
 *
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\NextGen\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use AuthentikApi\NextGen\ObjectSerializer;

/**
 * ApplicationRequest Class Doc Comment
 *
 * @description Application Serializer
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ApplicationRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ApplicationRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'name' => 'string',
        'slug' => 'string',
        'provider' => 'int',
        'backchannel_providers' => 'int[]',
        'open_in_new_tab' => 'bool',
        'meta_launch_url' => 'string',
        'meta_icon' => 'string',
        'meta_description' => 'string',
        'meta_publisher' => 'string',
        'policy_engine_mode' => '\AuthentikApi\NextGen\Model\PolicyEngineMode',
        'group' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'name' => null,
        'slug' => null,
        'provider' => null,
        'backchannel_providers' => null,
        'open_in_new_tab' => null,
        'meta_launch_url' => 'uri',
        'meta_icon' => null,
        'meta_description' => null,
        'meta_publisher' => null,
        'policy_engine_mode' => null,
        'group' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'name' => false,
        'slug' => false,
        'provider' => true,
        'backchannel_providers' => false,
        'open_in_new_tab' => false,
        'meta_launch_url' => false,
        'meta_icon' => false,
        'meta_description' => false,
        'meta_publisher' => false,
        'policy_engine_mode' => false,
        'group' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'name' => 'name',
        'slug' => 'slug',
        'provider' => 'provider',
        'backchannel_providers' => 'backchannel_providers',
        'open_in_new_tab' => 'open_in_new_tab',
        'meta_launch_url' => 'meta_launch_url',
        'meta_icon' => 'meta_icon',
        'meta_description' => 'meta_description',
        'meta_publisher' => 'meta_publisher',
        'policy_engine_mode' => 'policy_engine_mode',
        'group' => 'group'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'name' => 'setName',
        'slug' => 'setSlug',
        'provider' => 'setProvider',
        'backchannel_providers' => 'setBackchannelProviders',
        'open_in_new_tab' => 'setOpenInNewTab',
        'meta_launch_url' => 'setMetaLaunchUrl',
        'meta_icon' => 'setMetaIcon',
        'meta_description' => 'setMetaDescription',
        'meta_publisher' => 'setMetaPublisher',
        'policy_engine_mode' => 'setPolicyEngineMode',
        'group' => 'setGroup'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'name' => 'getName',
        'slug' => 'getSlug',
        'provider' => 'getProvider',
        'backchannel_providers' => 'getBackchannelProviders',
        'open_in_new_tab' => 'getOpenInNewTab',
        'meta_launch_url' => 'getMetaLaunchUrl',
        'meta_icon' => 'getMetaIcon',
        'meta_description' => 'getMetaDescription',
        'meta_publisher' => 'getMetaPublisher',
        'policy_engine_mode' => 'getPolicyEngineMode',
        'group' => 'getGroup'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('provider', $data ?? [], null);
        $this->setIfExists('backchannel_providers', $data ?? [], null);
        $this->setIfExists('open_in_new_tab', $data ?? [], null);
        $this->setIfExists('meta_launch_url', $data ?? [], null);
        $this->setIfExists('meta_icon', $data ?? [], null);
        $this->setIfExists('meta_description', $data ?? [], null);
        $this->setIfExists('meta_publisher', $data ?? [], null);
        $this->setIfExists('policy_engine_mode', $data ?? [], null);
        $this->setIfExists('group', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['slug'] === null) {
            $invalidProperties[] = "'slug' can't be null";
        }
        if ((mb_strlen($this->container['slug']) < 1)) {
            $invalidProperties[] = "invalid value for 'slug', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^[-a-zA-Z0-9_]+$/", $this->container['slug'])) {
            $invalidProperties[] = "invalid value for 'slug', must be conform to the pattern /^[-a-zA-Z0-9_]+$/.";
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Application's display Name.
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new InvalidArgumentException('invalid length for $name when calling ApplicationRequest., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string
     */
    public function getSlug(): string
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string $slug Internal application name, used in URLs.
     *
     * @return $this
     */
    public function setSlug(string $slug): static
    {
        if (is_null($slug)) {
            throw new InvalidArgumentException('non-nullable slug cannot be null');
        }

        if ((mb_strlen($slug) < 1)) {
            throw new InvalidArgumentException('invalid length for $slug when calling ApplicationRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[-a-zA-Z0-9_]+$/", ObjectSerializer::toString($slug)))) {
            throw new InvalidArgumentException("invalid value for \$slug when calling ApplicationRequest., must conform to the pattern /^[-a-zA-Z0-9_]+$/.");
        }

        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets provider
     *
     * @return int|null
     */
    public function getProvider(): ?int
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     *
     * @param int|null $provider provider
     *
     * @return $this
     */
    public function setProvider(?int $provider): static
    {
        if (is_null($provider)) {
            array_push($this->openAPINullablesSetToNull, 'provider');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('provider', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets backchannel_providers
     *
     * @return int[]|null
     */
    public function getBackchannelProviders(): ?array
    {
        return $this->container['backchannel_providers'];
    }

    /**
     * Sets backchannel_providers
     *
     * @param int[]|null $backchannel_providers backchannel_providers
     *
     * @return $this
     */
    public function setBackchannelProviders(?array $backchannel_providers): static
    {
        if (is_null($backchannel_providers)) {
            throw new InvalidArgumentException('non-nullable backchannel_providers cannot be null');
        }
        $this->container['backchannel_providers'] = $backchannel_providers;

        return $this;
    }

    /**
     * Gets open_in_new_tab
     *
     * @return bool|null
     */
    public function getOpenInNewTab(): ?bool
    {
        return $this->container['open_in_new_tab'];
    }

    /**
     * Sets open_in_new_tab
     *
     * @param bool|null $open_in_new_tab Open launch URL in a new browser tab or window.
     *
     * @return $this
     */
    public function setOpenInNewTab(?bool $open_in_new_tab): static
    {
        if (is_null($open_in_new_tab)) {
            throw new InvalidArgumentException('non-nullable open_in_new_tab cannot be null');
        }
        $this->container['open_in_new_tab'] = $open_in_new_tab;

        return $this;
    }

    /**
     * Gets meta_launch_url
     *
     * @return string|null
     */
    public function getMetaLaunchUrl(): ?string
    {
        return $this->container['meta_launch_url'];
    }

    /**
     * Sets meta_launch_url
     *
     * @param string|null $meta_launch_url meta_launch_url
     *
     * @return $this
     */
    public function setMetaLaunchUrl(?string $meta_launch_url): static
    {
        if (is_null($meta_launch_url)) {
            throw new InvalidArgumentException('non-nullable meta_launch_url cannot be null');
        }
        $this->container['meta_launch_url'] = $meta_launch_url;

        return $this;
    }

    /**
     * Gets meta_icon
     *
     * @return string|null
     */
    public function getMetaIcon(): ?string
    {
        return $this->container['meta_icon'];
    }

    /**
     * Sets meta_icon
     *
     * @param string|null $meta_icon meta_icon
     *
     * @return $this
     */
    public function setMetaIcon(?string $meta_icon): static
    {
        if (is_null($meta_icon)) {
            throw new InvalidArgumentException('non-nullable meta_icon cannot be null');
        }
        $this->container['meta_icon'] = $meta_icon;

        return $this;
    }

    /**
     * Gets meta_description
     *
     * @return string|null
     */
    public function getMetaDescription(): ?string
    {
        return $this->container['meta_description'];
    }

    /**
     * Sets meta_description
     *
     * @param string|null $meta_description meta_description
     *
     * @return $this
     */
    public function setMetaDescription(?string $meta_description): static
    {
        if (is_null($meta_description)) {
            throw new InvalidArgumentException('non-nullable meta_description cannot be null');
        }
        $this->container['meta_description'] = $meta_description;

        return $this;
    }

    /**
     * Gets meta_publisher
     *
     * @return string|null
     */
    public function getMetaPublisher(): ?string
    {
        return $this->container['meta_publisher'];
    }

    /**
     * Sets meta_publisher
     *
     * @param string|null $meta_publisher meta_publisher
     *
     * @return $this
     */
    public function setMetaPublisher(?string $meta_publisher): static
    {
        if (is_null($meta_publisher)) {
            throw new InvalidArgumentException('non-nullable meta_publisher cannot be null');
        }
        $this->container['meta_publisher'] = $meta_publisher;

        return $this;
    }

    /**
     * Gets policy_engine_mode
     *
     * @return \AuthentikApi\NextGen\Model\PolicyEngineMode|null
     */
    public function getPolicyEngineMode(): ?\AuthentikApi\NextGen\Model\PolicyEngineMode
    {
        return $this->container['policy_engine_mode'];
    }

    /**
     * Sets policy_engine_mode
     *
     * @param \AuthentikApi\NextGen\Model\PolicyEngineMode|null $policy_engine_mode policy_engine_mode
     *
     * @return $this
     */
    public function setPolicyEngineMode(?\AuthentikApi\NextGen\Model\PolicyEngineMode $policy_engine_mode): static
    {
        if (is_null($policy_engine_mode)) {
            throw new InvalidArgumentException('non-nullable policy_engine_mode cannot be null');
        }
        $this->container['policy_engine_mode'] = $policy_engine_mode;

        return $this;
    }

    /**
     * Gets group
     *
     * @return string|null
     */
    public function getGroup(): ?string
    {
        return $this->container['group'];
    }

    /**
     * Sets group
     *
     * @param string|null $group group
     *
     * @return $this
     */
    public function setGroup(?string $group): static
    {
        if (is_null($group)) {
            throw new InvalidArgumentException('non-nullable group cannot be null');
        }
        $this->container['group'] = $group;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


