<?php
/**
 * LDAPProviderRequest
 *
 * PHP version 8.1
 *
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\NextGen\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use AuthentikApi\NextGen\ObjectSerializer;

/**
 * LDAPProviderRequest Class Doc Comment
 *
 * @description LDAPProvider Serializer
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class LDAPProviderRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'LDAPProviderRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'name' => 'string',
        'authentication_flow' => 'string',
        'authorization_flow' => 'string',
        'invalidation_flow' => 'string',
        'property_mappings' => 'string[]',
        'base_dn' => 'string',
        'certificate' => 'string',
        'tls_server_name' => 'string',
        'uid_start_number' => 'int',
        'gid_start_number' => 'int',
        'search_mode' => '\AuthentikApi\NextGen\Model\LDAPAPIAccessMode',
        'bind_mode' => '\AuthentikApi\NextGen\Model\LDAPAPIAccessMode',
        'mfa_support' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'name' => null,
        'authentication_flow' => 'uuid',
        'authorization_flow' => 'uuid',
        'invalidation_flow' => 'uuid',
        'property_mappings' => 'uuid',
        'base_dn' => null,
        'certificate' => 'uuid',
        'tls_server_name' => null,
        'uid_start_number' => null,
        'gid_start_number' => null,
        'search_mode' => null,
        'bind_mode' => null,
        'mfa_support' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'name' => false,
        'authentication_flow' => true,
        'authorization_flow' => false,
        'invalidation_flow' => false,
        'property_mappings' => false,
        'base_dn' => false,
        'certificate' => true,
        'tls_server_name' => false,
        'uid_start_number' => false,
        'gid_start_number' => false,
        'search_mode' => false,
        'bind_mode' => false,
        'mfa_support' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'name' => 'name',
        'authentication_flow' => 'authentication_flow',
        'authorization_flow' => 'authorization_flow',
        'invalidation_flow' => 'invalidation_flow',
        'property_mappings' => 'property_mappings',
        'base_dn' => 'base_dn',
        'certificate' => 'certificate',
        'tls_server_name' => 'tls_server_name',
        'uid_start_number' => 'uid_start_number',
        'gid_start_number' => 'gid_start_number',
        'search_mode' => 'search_mode',
        'bind_mode' => 'bind_mode',
        'mfa_support' => 'mfa_support'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'name' => 'setName',
        'authentication_flow' => 'setAuthenticationFlow',
        'authorization_flow' => 'setAuthorizationFlow',
        'invalidation_flow' => 'setInvalidationFlow',
        'property_mappings' => 'setPropertyMappings',
        'base_dn' => 'setBaseDn',
        'certificate' => 'setCertificate',
        'tls_server_name' => 'setTlsServerName',
        'uid_start_number' => 'setUidStartNumber',
        'gid_start_number' => 'setGidStartNumber',
        'search_mode' => 'setSearchMode',
        'bind_mode' => 'setBindMode',
        'mfa_support' => 'setMfaSupport'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'name' => 'getName',
        'authentication_flow' => 'getAuthenticationFlow',
        'authorization_flow' => 'getAuthorizationFlow',
        'invalidation_flow' => 'getInvalidationFlow',
        'property_mappings' => 'getPropertyMappings',
        'base_dn' => 'getBaseDn',
        'certificate' => 'getCertificate',
        'tls_server_name' => 'getTlsServerName',
        'uid_start_number' => 'getUidStartNumber',
        'gid_start_number' => 'getGidStartNumber',
        'search_mode' => 'getSearchMode',
        'bind_mode' => 'getBindMode',
        'mfa_support' => 'getMfaSupport'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('authentication_flow', $data ?? [], null);
        $this->setIfExists('authorization_flow', $data ?? [], null);
        $this->setIfExists('invalidation_flow', $data ?? [], null);
        $this->setIfExists('property_mappings', $data ?? [], null);
        $this->setIfExists('base_dn', $data ?? [], null);
        $this->setIfExists('certificate', $data ?? [], null);
        $this->setIfExists('tls_server_name', $data ?? [], null);
        $this->setIfExists('uid_start_number', $data ?? [], null);
        $this->setIfExists('gid_start_number', $data ?? [], null);
        $this->setIfExists('search_mode', $data ?? [], null);
        $this->setIfExists('bind_mode', $data ?? [], null);
        $this->setIfExists('mfa_support', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['authorization_flow'] === null) {
            $invalidProperties[] = "'authorization_flow' can't be null";
        }
        if ($this->container['invalidation_flow'] === null) {
            $invalidProperties[] = "'invalidation_flow' can't be null";
        }
        if (!is_null($this->container['base_dn']) && (mb_strlen($this->container['base_dn']) < 1)) {
            $invalidProperties[] = "invalid value for 'base_dn', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['uid_start_number']) && ($this->container['uid_start_number'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'uid_start_number', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['uid_start_number']) && ($this->container['uid_start_number'] < -2147483648)) {
            $invalidProperties[] = "invalid value for 'uid_start_number', must be bigger than or equal to -2147483648.";
        }

        if (!is_null($this->container['gid_start_number']) && ($this->container['gid_start_number'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'gid_start_number', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['gid_start_number']) && ($this->container['gid_start_number'] < -2147483648)) {
            $invalidProperties[] = "invalid value for 'gid_start_number', must be bigger than or equal to -2147483648.";
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new InvalidArgumentException('invalid length for $name when calling LDAPProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets authentication_flow
     *
     * @return string|null
     */
    public function getAuthenticationFlow(): ?string
    {
        return $this->container['authentication_flow'];
    }

    /**
     * Sets authentication_flow
     *
     * @param string|null $authentication_flow Flow used for authentication when the associated application is accessed by an un-authenticated user.
     *
     * @return $this
     */
    public function setAuthenticationFlow(?string $authentication_flow): static
    {
        if (is_null($authentication_flow)) {
            array_push($this->openAPINullablesSetToNull, 'authentication_flow');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authentication_flow', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authentication_flow'] = $authentication_flow;

        return $this;
    }

    /**
     * Gets authorization_flow
     *
     * @return string
     */
    public function getAuthorizationFlow(): string
    {
        return $this->container['authorization_flow'];
    }

    /**
     * Sets authorization_flow
     *
     * @param string $authorization_flow Flow used when authorizing this provider.
     *
     * @return $this
     */
    public function setAuthorizationFlow(string $authorization_flow): static
    {
        if (is_null($authorization_flow)) {
            throw new InvalidArgumentException('non-nullable authorization_flow cannot be null');
        }
        $this->container['authorization_flow'] = $authorization_flow;

        return $this;
    }

    /**
     * Gets invalidation_flow
     *
     * @return string
     */
    public function getInvalidationFlow(): string
    {
        return $this->container['invalidation_flow'];
    }

    /**
     * Sets invalidation_flow
     *
     * @param string $invalidation_flow Flow used ending the session from a provider.
     *
     * @return $this
     */
    public function setInvalidationFlow(string $invalidation_flow): static
    {
        if (is_null($invalidation_flow)) {
            throw new InvalidArgumentException('non-nullable invalidation_flow cannot be null');
        }
        $this->container['invalidation_flow'] = $invalidation_flow;

        return $this;
    }

    /**
     * Gets property_mappings
     *
     * @return string[]|null
     */
    public function getPropertyMappings(): ?array
    {
        return $this->container['property_mappings'];
    }

    /**
     * Sets property_mappings
     *
     * @param string[]|null $property_mappings property_mappings
     *
     * @return $this
     */
    public function setPropertyMappings(?array $property_mappings): static
    {
        if (is_null($property_mappings)) {
            throw new InvalidArgumentException('non-nullable property_mappings cannot be null');
        }
        $this->container['property_mappings'] = $property_mappings;

        return $this;
    }

    /**
     * Gets base_dn
     *
     * @return string|null
     */
    public function getBaseDn(): ?string
    {
        return $this->container['base_dn'];
    }

    /**
     * Sets base_dn
     *
     * @param string|null $base_dn DN under which objects are accessible.
     *
     * @return $this
     */
    public function setBaseDn(?string $base_dn): static
    {
        if (is_null($base_dn)) {
            throw new InvalidArgumentException('non-nullable base_dn cannot be null');
        }

        if ((mb_strlen($base_dn) < 1)) {
            throw new InvalidArgumentException('invalid length for $base_dn when calling LDAPProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['base_dn'] = $base_dn;

        return $this;
    }

    /**
     * Gets certificate
     *
     * @return string|null
     */
    public function getCertificate(): ?string
    {
        return $this->container['certificate'];
    }

    /**
     * Sets certificate
     *
     * @param string|null $certificate certificate
     *
     * @return $this
     */
    public function setCertificate(?string $certificate): static
    {
        if (is_null($certificate)) {
            array_push($this->openAPINullablesSetToNull, 'certificate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('certificate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['certificate'] = $certificate;

        return $this;
    }

    /**
     * Gets tls_server_name
     *
     * @return string|null
     */
    public function getTlsServerName(): ?string
    {
        return $this->container['tls_server_name'];
    }

    /**
     * Sets tls_server_name
     *
     * @param string|null $tls_server_name tls_server_name
     *
     * @return $this
     */
    public function setTlsServerName(?string $tls_server_name): static
    {
        if (is_null($tls_server_name)) {
            throw new InvalidArgumentException('non-nullable tls_server_name cannot be null');
        }
        $this->container['tls_server_name'] = $tls_server_name;

        return $this;
    }

    /**
     * Gets uid_start_number
     *
     * @return int|null
     */
    public function getUidStartNumber(): ?int
    {
        return $this->container['uid_start_number'];
    }

    /**
     * Sets uid_start_number
     *
     * @param int|null $uid_start_number The start for uidNumbers, this number is added to the user.pk to make sure that the numbers aren't too low for POSIX users. Default is 2000 to ensure that we don't collide with local users uidNumber
     *
     * @return $this
     */
    public function setUidStartNumber(?int $uid_start_number): static
    {
        if (is_null($uid_start_number)) {
            throw new InvalidArgumentException('non-nullable uid_start_number cannot be null');
        }

        if (($uid_start_number > 2147483647)) {
            throw new InvalidArgumentException('invalid value for $uid_start_number when calling LDAPProviderRequest., must be smaller than or equal to 2147483647.');
        }
        if (($uid_start_number < -2147483648)) {
            throw new InvalidArgumentException('invalid value for $uid_start_number when calling LDAPProviderRequest., must be bigger than or equal to -2147483648.');
        }

        $this->container['uid_start_number'] = $uid_start_number;

        return $this;
    }

    /**
     * Gets gid_start_number
     *
     * @return int|null
     */
    public function getGidStartNumber(): ?int
    {
        return $this->container['gid_start_number'];
    }

    /**
     * Sets gid_start_number
     *
     * @param int|null $gid_start_number The start for gidNumbers, this number is added to a number generated from the group.pk to make sure that the numbers aren't too low for POSIX groups. Default is 4000 to ensure that we don't collide with local groups or users primary groups gidNumber
     *
     * @return $this
     */
    public function setGidStartNumber(?int $gid_start_number): static
    {
        if (is_null($gid_start_number)) {
            throw new InvalidArgumentException('non-nullable gid_start_number cannot be null');
        }

        if (($gid_start_number > 2147483647)) {
            throw new InvalidArgumentException('invalid value for $gid_start_number when calling LDAPProviderRequest., must be smaller than or equal to 2147483647.');
        }
        if (($gid_start_number < -2147483648)) {
            throw new InvalidArgumentException('invalid value for $gid_start_number when calling LDAPProviderRequest., must be bigger than or equal to -2147483648.');
        }

        $this->container['gid_start_number'] = $gid_start_number;

        return $this;
    }

    /**
     * Gets search_mode
     *
     * @return \AuthentikApi\NextGen\Model\LDAPAPIAccessMode|null
     */
    public function getSearchMode(): ?\AuthentikApi\NextGen\Model\LDAPAPIAccessMode
    {
        return $this->container['search_mode'];
    }

    /**
     * Sets search_mode
     *
     * @param \AuthentikApi\NextGen\Model\LDAPAPIAccessMode|null $search_mode search_mode
     *
     * @return $this
     */
    public function setSearchMode(?\AuthentikApi\NextGen\Model\LDAPAPIAccessMode $search_mode): static
    {
        if (is_null($search_mode)) {
            throw new InvalidArgumentException('non-nullable search_mode cannot be null');
        }
        $this->container['search_mode'] = $search_mode;

        return $this;
    }

    /**
     * Gets bind_mode
     *
     * @return \AuthentikApi\NextGen\Model\LDAPAPIAccessMode|null
     */
    public function getBindMode(): ?\AuthentikApi\NextGen\Model\LDAPAPIAccessMode
    {
        return $this->container['bind_mode'];
    }

    /**
     * Sets bind_mode
     *
     * @param \AuthentikApi\NextGen\Model\LDAPAPIAccessMode|null $bind_mode bind_mode
     *
     * @return $this
     */
    public function setBindMode(?\AuthentikApi\NextGen\Model\LDAPAPIAccessMode $bind_mode): static
    {
        if (is_null($bind_mode)) {
            throw new InvalidArgumentException('non-nullable bind_mode cannot be null');
        }
        $this->container['bind_mode'] = $bind_mode;

        return $this;
    }

    /**
     * Gets mfa_support
     *
     * @return bool|null
     */
    public function getMfaSupport(): ?bool
    {
        return $this->container['mfa_support'];
    }

    /**
     * Sets mfa_support
     *
     * @param bool|null $mfa_support When enabled, code-based multi-factor authentication can be used by appending a semicolon and the TOTP code to the password. This should only be enabled if all users that will bind to this provider have a TOTP device configured, as otherwise a password may incorrectly be rejected if it contains a semicolon.
     *
     * @return $this
     */
    public function setMfaSupport(?bool $mfa_support): static
    {
        if (is_null($mfa_support)) {
            throw new InvalidArgumentException('non-nullable mfa_support cannot be null');
        }
        $this->container['mfa_support'] = $mfa_support;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


