<?php
/**
 * OAuth2ProviderRequest
 *
 * PHP version 8.1
 *
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\NextGen\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use AuthentikApi\NextGen\ObjectSerializer;

/**
 * OAuth2ProviderRequest Class Doc Comment
 *
 * @description OAuth2Provider Serializer
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class OAuth2ProviderRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'OAuth2ProviderRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'name' => 'string',
        'authentication_flow' => 'string',
        'authorization_flow' => 'string',
        'invalidation_flow' => 'string',
        'property_mappings' => 'string[]',
        'client_type' => '\AuthentikApi\NextGen\Model\ClientTypeEnum',
        'client_id' => 'string',
        'client_secret' => 'string',
        'access_code_validity' => 'string',
        'access_token_validity' => 'string',
        'refresh_token_validity' => 'string',
        'refresh_token_threshold' => 'string',
        'include_claims_in_id_token' => 'bool',
        'signing_key' => 'string',
        'encryption_key' => 'string',
        'redirect_uris' => '\AuthentikApi\NextGen\Model\RedirectURIRequest[]',
        'logout_uri' => 'string',
        'logout_method' => '\AuthentikApi\NextGen\Model\OAuth2ProviderLogoutMethodEnum',
        'sub_mode' => '\AuthentikApi\NextGen\Model\SubModeEnum',
        'issuer_mode' => '\AuthentikApi\NextGen\Model\IssuerModeEnum',
        'jwt_federation_sources' => 'string[]',
        'jwt_federation_providers' => 'int[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'name' => null,
        'authentication_flow' => 'uuid',
        'authorization_flow' => 'uuid',
        'invalidation_flow' => 'uuid',
        'property_mappings' => 'uuid',
        'client_type' => null,
        'client_id' => null,
        'client_secret' => null,
        'access_code_validity' => null,
        'access_token_validity' => null,
        'refresh_token_validity' => null,
        'refresh_token_threshold' => null,
        'include_claims_in_id_token' => null,
        'signing_key' => 'uuid',
        'encryption_key' => 'uuid',
        'redirect_uris' => null,
        'logout_uri' => 'uri',
        'logout_method' => null,
        'sub_mode' => null,
        'issuer_mode' => null,
        'jwt_federation_sources' => 'uuid',
        'jwt_federation_providers' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'name' => false,
        'authentication_flow' => true,
        'authorization_flow' => false,
        'invalidation_flow' => false,
        'property_mappings' => false,
        'client_type' => false,
        'client_id' => false,
        'client_secret' => false,
        'access_code_validity' => false,
        'access_token_validity' => false,
        'refresh_token_validity' => false,
        'refresh_token_threshold' => false,
        'include_claims_in_id_token' => false,
        'signing_key' => true,
        'encryption_key' => true,
        'redirect_uris' => false,
        'logout_uri' => false,
        'logout_method' => false,
        'sub_mode' => false,
        'issuer_mode' => false,
        'jwt_federation_sources' => false,
        'jwt_federation_providers' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'name' => 'name',
        'authentication_flow' => 'authentication_flow',
        'authorization_flow' => 'authorization_flow',
        'invalidation_flow' => 'invalidation_flow',
        'property_mappings' => 'property_mappings',
        'client_type' => 'client_type',
        'client_id' => 'client_id',
        'client_secret' => 'client_secret',
        'access_code_validity' => 'access_code_validity',
        'access_token_validity' => 'access_token_validity',
        'refresh_token_validity' => 'refresh_token_validity',
        'refresh_token_threshold' => 'refresh_token_threshold',
        'include_claims_in_id_token' => 'include_claims_in_id_token',
        'signing_key' => 'signing_key',
        'encryption_key' => 'encryption_key',
        'redirect_uris' => 'redirect_uris',
        'logout_uri' => 'logout_uri',
        'logout_method' => 'logout_method',
        'sub_mode' => 'sub_mode',
        'issuer_mode' => 'issuer_mode',
        'jwt_federation_sources' => 'jwt_federation_sources',
        'jwt_federation_providers' => 'jwt_federation_providers'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'name' => 'setName',
        'authentication_flow' => 'setAuthenticationFlow',
        'authorization_flow' => 'setAuthorizationFlow',
        'invalidation_flow' => 'setInvalidationFlow',
        'property_mappings' => 'setPropertyMappings',
        'client_type' => 'setClientType',
        'client_id' => 'setClientId',
        'client_secret' => 'setClientSecret',
        'access_code_validity' => 'setAccessCodeValidity',
        'access_token_validity' => 'setAccessTokenValidity',
        'refresh_token_validity' => 'setRefreshTokenValidity',
        'refresh_token_threshold' => 'setRefreshTokenThreshold',
        'include_claims_in_id_token' => 'setIncludeClaimsInIdToken',
        'signing_key' => 'setSigningKey',
        'encryption_key' => 'setEncryptionKey',
        'redirect_uris' => 'setRedirectUris',
        'logout_uri' => 'setLogoutUri',
        'logout_method' => 'setLogoutMethod',
        'sub_mode' => 'setSubMode',
        'issuer_mode' => 'setIssuerMode',
        'jwt_federation_sources' => 'setJwtFederationSources',
        'jwt_federation_providers' => 'setJwtFederationProviders'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'name' => 'getName',
        'authentication_flow' => 'getAuthenticationFlow',
        'authorization_flow' => 'getAuthorizationFlow',
        'invalidation_flow' => 'getInvalidationFlow',
        'property_mappings' => 'getPropertyMappings',
        'client_type' => 'getClientType',
        'client_id' => 'getClientId',
        'client_secret' => 'getClientSecret',
        'access_code_validity' => 'getAccessCodeValidity',
        'access_token_validity' => 'getAccessTokenValidity',
        'refresh_token_validity' => 'getRefreshTokenValidity',
        'refresh_token_threshold' => 'getRefreshTokenThreshold',
        'include_claims_in_id_token' => 'getIncludeClaimsInIdToken',
        'signing_key' => 'getSigningKey',
        'encryption_key' => 'getEncryptionKey',
        'redirect_uris' => 'getRedirectUris',
        'logout_uri' => 'getLogoutUri',
        'logout_method' => 'getLogoutMethod',
        'sub_mode' => 'getSubMode',
        'issuer_mode' => 'getIssuerMode',
        'jwt_federation_sources' => 'getJwtFederationSources',
        'jwt_federation_providers' => 'getJwtFederationProviders'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('authentication_flow', $data ?? [], null);
        $this->setIfExists('authorization_flow', $data ?? [], null);
        $this->setIfExists('invalidation_flow', $data ?? [], null);
        $this->setIfExists('property_mappings', $data ?? [], null);
        $this->setIfExists('client_type', $data ?? [], null);
        $this->setIfExists('client_id', $data ?? [], null);
        $this->setIfExists('client_secret', $data ?? [], null);
        $this->setIfExists('access_code_validity', $data ?? [], null);
        $this->setIfExists('access_token_validity', $data ?? [], null);
        $this->setIfExists('refresh_token_validity', $data ?? [], null);
        $this->setIfExists('refresh_token_threshold', $data ?? [], null);
        $this->setIfExists('include_claims_in_id_token', $data ?? [], null);
        $this->setIfExists('signing_key', $data ?? [], null);
        $this->setIfExists('encryption_key', $data ?? [], null);
        $this->setIfExists('redirect_uris', $data ?? [], null);
        $this->setIfExists('logout_uri', $data ?? [], null);
        $this->setIfExists('logout_method', $data ?? [], null);
        $this->setIfExists('sub_mode', $data ?? [], null);
        $this->setIfExists('issuer_mode', $data ?? [], null);
        $this->setIfExists('jwt_federation_sources', $data ?? [], null);
        $this->setIfExists('jwt_federation_providers', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['authorization_flow'] === null) {
            $invalidProperties[] = "'authorization_flow' can't be null";
        }
        if ($this->container['invalidation_flow'] === null) {
            $invalidProperties[] = "'invalidation_flow' can't be null";
        }
        if (!is_null($this->container['client_id']) && (mb_strlen($this->container['client_id']) > 255)) {
            $invalidProperties[] = "invalid value for 'client_id', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['client_id']) && (mb_strlen($this->container['client_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'client_id', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['client_secret']) && (mb_strlen($this->container['client_secret']) > 255)) {
            $invalidProperties[] = "invalid value for 'client_secret', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['access_code_validity']) && (mb_strlen($this->container['access_code_validity']) < 1)) {
            $invalidProperties[] = "invalid value for 'access_code_validity', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['access_token_validity']) && (mb_strlen($this->container['access_token_validity']) < 1)) {
            $invalidProperties[] = "invalid value for 'access_token_validity', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['refresh_token_validity']) && (mb_strlen($this->container['refresh_token_validity']) < 1)) {
            $invalidProperties[] = "invalid value for 'refresh_token_validity', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['refresh_token_threshold']) && (mb_strlen($this->container['refresh_token_threshold']) < 1)) {
            $invalidProperties[] = "invalid value for 'refresh_token_threshold', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['redirect_uris'] === null) {
            $invalidProperties[] = "'redirect_uris' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new InvalidArgumentException('invalid length for $name when calling OAuth2ProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets authentication_flow
     *
     * @return string|null
     */
    public function getAuthenticationFlow(): ?string
    {
        return $this->container['authentication_flow'];
    }

    /**
     * Sets authentication_flow
     *
     * @param string|null $authentication_flow Flow used for authentication when the associated application is accessed by an un-authenticated user.
     *
     * @return $this
     */
    public function setAuthenticationFlow(?string $authentication_flow): static
    {
        if (is_null($authentication_flow)) {
            array_push($this->openAPINullablesSetToNull, 'authentication_flow');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authentication_flow', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authentication_flow'] = $authentication_flow;

        return $this;
    }

    /**
     * Gets authorization_flow
     *
     * @return string
     */
    public function getAuthorizationFlow(): string
    {
        return $this->container['authorization_flow'];
    }

    /**
     * Sets authorization_flow
     *
     * @param string $authorization_flow Flow used when authorizing this provider.
     *
     * @return $this
     */
    public function setAuthorizationFlow(string $authorization_flow): static
    {
        if (is_null($authorization_flow)) {
            throw new InvalidArgumentException('non-nullable authorization_flow cannot be null');
        }
        $this->container['authorization_flow'] = $authorization_flow;

        return $this;
    }

    /**
     * Gets invalidation_flow
     *
     * @return string
     */
    public function getInvalidationFlow(): string
    {
        return $this->container['invalidation_flow'];
    }

    /**
     * Sets invalidation_flow
     *
     * @param string $invalidation_flow Flow used ending the session from a provider.
     *
     * @return $this
     */
    public function setInvalidationFlow(string $invalidation_flow): static
    {
        if (is_null($invalidation_flow)) {
            throw new InvalidArgumentException('non-nullable invalidation_flow cannot be null');
        }
        $this->container['invalidation_flow'] = $invalidation_flow;

        return $this;
    }

    /**
     * Gets property_mappings
     *
     * @return string[]|null
     */
    public function getPropertyMappings(): ?array
    {
        return $this->container['property_mappings'];
    }

    /**
     * Sets property_mappings
     *
     * @param string[]|null $property_mappings property_mappings
     *
     * @return $this
     */
    public function setPropertyMappings(?array $property_mappings): static
    {
        if (is_null($property_mappings)) {
            throw new InvalidArgumentException('non-nullable property_mappings cannot be null');
        }
        $this->container['property_mappings'] = $property_mappings;

        return $this;
    }

    /**
     * Gets client_type
     *
     * @return \AuthentikApi\NextGen\Model\ClientTypeEnum|null
     */
    public function getClientType(): ?\AuthentikApi\NextGen\Model\ClientTypeEnum
    {
        return $this->container['client_type'];
    }

    /**
     * Sets client_type
     *
     * @param \AuthentikApi\NextGen\Model\ClientTypeEnum|null $client_type Confidential clients are capable of maintaining the confidentiality of their credentials. Public clients are incapable
     *
     * @return $this
     */
    public function setClientType(?\AuthentikApi\NextGen\Model\ClientTypeEnum $client_type): static
    {
        if (is_null($client_type)) {
            throw new InvalidArgumentException('non-nullable client_type cannot be null');
        }
        $this->container['client_type'] = $client_type;

        return $this;
    }

    /**
     * Gets client_id
     *
     * @return string|null
     */
    public function getClientId(): ?string
    {
        return $this->container['client_id'];
    }

    /**
     * Sets client_id
     *
     * @param string|null $client_id client_id
     *
     * @return $this
     */
    public function setClientId(?string $client_id): static
    {
        if (is_null($client_id)) {
            throw new InvalidArgumentException('non-nullable client_id cannot be null');
        }
        if ((mb_strlen($client_id) > 255)) {
            throw new InvalidArgumentException('invalid length for $client_id when calling OAuth2ProviderRequest., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($client_id) < 1)) {
            throw new InvalidArgumentException('invalid length for $client_id when calling OAuth2ProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['client_id'] = $client_id;

        return $this;
    }

    /**
     * Gets client_secret
     *
     * @return string|null
     */
    public function getClientSecret(): ?string
    {
        return $this->container['client_secret'];
    }

    /**
     * Sets client_secret
     *
     * @param string|null $client_secret client_secret
     *
     * @return $this
     */
    public function setClientSecret(?string $client_secret): static
    {
        if (is_null($client_secret)) {
            throw new InvalidArgumentException('non-nullable client_secret cannot be null');
        }
        if ((mb_strlen($client_secret) > 255)) {
            throw new InvalidArgumentException('invalid length for $client_secret when calling OAuth2ProviderRequest., must be smaller than or equal to 255.');
        }

        $this->container['client_secret'] = $client_secret;

        return $this;
    }

    /**
     * Gets access_code_validity
     *
     * @return string|null
     */
    public function getAccessCodeValidity(): ?string
    {
        return $this->container['access_code_validity'];
    }

    /**
     * Sets access_code_validity
     *
     * @param string|null $access_code_validity Access codes not valid on or after current time + this value (Format: hours=1;minutes=2;seconds=3).
     *
     * @return $this
     */
    public function setAccessCodeValidity(?string $access_code_validity): static
    {
        if (is_null($access_code_validity)) {
            throw new InvalidArgumentException('non-nullable access_code_validity cannot be null');
        }

        if ((mb_strlen($access_code_validity) < 1)) {
            throw new InvalidArgumentException('invalid length for $access_code_validity when calling OAuth2ProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['access_code_validity'] = $access_code_validity;

        return $this;
    }

    /**
     * Gets access_token_validity
     *
     * @return string|null
     */
    public function getAccessTokenValidity(): ?string
    {
        return $this->container['access_token_validity'];
    }

    /**
     * Sets access_token_validity
     *
     * @param string|null $access_token_validity Tokens not valid on or after current time + this value (Format: hours=1;minutes=2;seconds=3).
     *
     * @return $this
     */
    public function setAccessTokenValidity(?string $access_token_validity): static
    {
        if (is_null($access_token_validity)) {
            throw new InvalidArgumentException('non-nullable access_token_validity cannot be null');
        }

        if ((mb_strlen($access_token_validity) < 1)) {
            throw new InvalidArgumentException('invalid length for $access_token_validity when calling OAuth2ProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['access_token_validity'] = $access_token_validity;

        return $this;
    }

    /**
     * Gets refresh_token_validity
     *
     * @return string|null
     */
    public function getRefreshTokenValidity(): ?string
    {
        return $this->container['refresh_token_validity'];
    }

    /**
     * Sets refresh_token_validity
     *
     * @param string|null $refresh_token_validity Tokens not valid on or after current time + this value (Format: hours=1;minutes=2;seconds=3).
     *
     * @return $this
     */
    public function setRefreshTokenValidity(?string $refresh_token_validity): static
    {
        if (is_null($refresh_token_validity)) {
            throw new InvalidArgumentException('non-nullable refresh_token_validity cannot be null');
        }

        if ((mb_strlen($refresh_token_validity) < 1)) {
            throw new InvalidArgumentException('invalid length for $refresh_token_validity when calling OAuth2ProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['refresh_token_validity'] = $refresh_token_validity;

        return $this;
    }

    /**
     * Gets refresh_token_threshold
     *
     * @return string|null
     */
    public function getRefreshTokenThreshold(): ?string
    {
        return $this->container['refresh_token_threshold'];
    }

    /**
     * Sets refresh_token_threshold
     *
     * @param string|null $refresh_token_threshold When refreshing a token, if the refresh token is valid for less than this duration, it will be renewed. When set to seconds=0, token will always be renewed. (Format: hours=1;minutes=2;seconds=3).
     *
     * @return $this
     */
    public function setRefreshTokenThreshold(?string $refresh_token_threshold): static
    {
        if (is_null($refresh_token_threshold)) {
            throw new InvalidArgumentException('non-nullable refresh_token_threshold cannot be null');
        }

        if ((mb_strlen($refresh_token_threshold) < 1)) {
            throw new InvalidArgumentException('invalid length for $refresh_token_threshold when calling OAuth2ProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['refresh_token_threshold'] = $refresh_token_threshold;

        return $this;
    }

    /**
     * Gets include_claims_in_id_token
     *
     * @return bool|null
     */
    public function getIncludeClaimsInIdToken(): ?bool
    {
        return $this->container['include_claims_in_id_token'];
    }

    /**
     * Sets include_claims_in_id_token
     *
     * @param bool|null $include_claims_in_id_token Include User claims from scopes in the id_token, for applications that don't access the userinfo endpoint.
     *
     * @return $this
     */
    public function setIncludeClaimsInIdToken(?bool $include_claims_in_id_token): static
    {
        if (is_null($include_claims_in_id_token)) {
            throw new InvalidArgumentException('non-nullable include_claims_in_id_token cannot be null');
        }
        $this->container['include_claims_in_id_token'] = $include_claims_in_id_token;

        return $this;
    }

    /**
     * Gets signing_key
     *
     * @return string|null
     */
    public function getSigningKey(): ?string
    {
        return $this->container['signing_key'];
    }

    /**
     * Sets signing_key
     *
     * @param string|null $signing_key Key used to sign the tokens.
     *
     * @return $this
     */
    public function setSigningKey(?string $signing_key): static
    {
        if (is_null($signing_key)) {
            array_push($this->openAPINullablesSetToNull, 'signing_key');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('signing_key', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['signing_key'] = $signing_key;

        return $this;
    }

    /**
     * Gets encryption_key
     *
     * @return string|null
     */
    public function getEncryptionKey(): ?string
    {
        return $this->container['encryption_key'];
    }

    /**
     * Sets encryption_key
     *
     * @param string|null $encryption_key Key used to encrypt the tokens. When set, tokens will be encrypted and returned as JWEs.
     *
     * @return $this
     */
    public function setEncryptionKey(?string $encryption_key): static
    {
        if (is_null($encryption_key)) {
            array_push($this->openAPINullablesSetToNull, 'encryption_key');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('encryption_key', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['encryption_key'] = $encryption_key;

        return $this;
    }

    /**
     * Gets redirect_uris
     *
     * @return \AuthentikApi\NextGen\Model\RedirectURIRequest[]
     */
    public function getRedirectUris(): array
    {
        return $this->container['redirect_uris'];
    }

    /**
     * Sets redirect_uris
     *
     * @param \AuthentikApi\NextGen\Model\RedirectURIRequest[] $redirect_uris redirect_uris
     *
     * @return $this
     */
    public function setRedirectUris(array $redirect_uris): static
    {
        if (is_null($redirect_uris)) {
            throw new InvalidArgumentException('non-nullable redirect_uris cannot be null');
        }
        $this->container['redirect_uris'] = $redirect_uris;

        return $this;
    }

    /**
     * Gets logout_uri
     *
     * @return string|null
     */
    public function getLogoutUri(): ?string
    {
        return $this->container['logout_uri'];
    }

    /**
     * Sets logout_uri
     *
     * @param string|null $logout_uri logout_uri
     *
     * @return $this
     */
    public function setLogoutUri(?string $logout_uri): static
    {
        if (is_null($logout_uri)) {
            throw new InvalidArgumentException('non-nullable logout_uri cannot be null');
        }
        $this->container['logout_uri'] = $logout_uri;

        return $this;
    }

    /**
     * Gets logout_method
     *
     * @return \AuthentikApi\NextGen\Model\OAuth2ProviderLogoutMethodEnum|null
     */
    public function getLogoutMethod(): ?\AuthentikApi\NextGen\Model\OAuth2ProviderLogoutMethodEnum
    {
        return $this->container['logout_method'];
    }

    /**
     * Sets logout_method
     *
     * @param \AuthentikApi\NextGen\Model\OAuth2ProviderLogoutMethodEnum|null $logout_method Backchannel logs out with server to server calls. Frontchannel uses iframes in your browser
     *
     * @return $this
     */
    public function setLogoutMethod(?\AuthentikApi\NextGen\Model\OAuth2ProviderLogoutMethodEnum $logout_method): static
    {
        if (is_null($logout_method)) {
            throw new InvalidArgumentException('non-nullable logout_method cannot be null');
        }
        $this->container['logout_method'] = $logout_method;

        return $this;
    }

    /**
     * Gets sub_mode
     *
     * @return \AuthentikApi\NextGen\Model\SubModeEnum|null
     */
    public function getSubMode(): ?\AuthentikApi\NextGen\Model\SubModeEnum
    {
        return $this->container['sub_mode'];
    }

    /**
     * Sets sub_mode
     *
     * @param \AuthentikApi\NextGen\Model\SubModeEnum|null $sub_mode Configure what data should be used as unique User Identifier. For most cases, the default should be fine.
     *
     * @return $this
     */
    public function setSubMode(?\AuthentikApi\NextGen\Model\SubModeEnum $sub_mode): static
    {
        if (is_null($sub_mode)) {
            throw new InvalidArgumentException('non-nullable sub_mode cannot be null');
        }
        $this->container['sub_mode'] = $sub_mode;

        return $this;
    }

    /**
     * Gets issuer_mode
     *
     * @return \AuthentikApi\NextGen\Model\IssuerModeEnum|null
     */
    public function getIssuerMode(): ?\AuthentikApi\NextGen\Model\IssuerModeEnum
    {
        return $this->container['issuer_mode'];
    }

    /**
     * Sets issuer_mode
     *
     * @param \AuthentikApi\NextGen\Model\IssuerModeEnum|null $issuer_mode Configure how the issuer field of the ID Token should be filled.
     *
     * @return $this
     */
    public function setIssuerMode(?\AuthentikApi\NextGen\Model\IssuerModeEnum $issuer_mode): static
    {
        if (is_null($issuer_mode)) {
            throw new InvalidArgumentException('non-nullable issuer_mode cannot be null');
        }
        $this->container['issuer_mode'] = $issuer_mode;

        return $this;
    }

    /**
     * Gets jwt_federation_sources
     *
     * @return string[]|null
     */
    public function getJwtFederationSources(): ?array
    {
        return $this->container['jwt_federation_sources'];
    }

    /**
     * Sets jwt_federation_sources
     *
     * @param string[]|null $jwt_federation_sources jwt_federation_sources
     *
     * @return $this
     */
    public function setJwtFederationSources(?array $jwt_federation_sources): static
    {
        if (is_null($jwt_federation_sources)) {
            throw new InvalidArgumentException('non-nullable jwt_federation_sources cannot be null');
        }
        $this->container['jwt_federation_sources'] = $jwt_federation_sources;

        return $this;
    }

    /**
     * Gets jwt_federation_providers
     *
     * @return int[]|null
     */
    public function getJwtFederationProviders(): ?array
    {
        return $this->container['jwt_federation_providers'];
    }

    /**
     * Sets jwt_federation_providers
     *
     * @param int[]|null $jwt_federation_providers jwt_federation_providers
     *
     * @return $this
     */
    public function setJwtFederationProviders(?array $jwt_federation_providers): static
    {
        if (is_null($jwt_federation_providers)) {
            throw new InvalidArgumentException('non-nullable jwt_federation_providers cannot be null');
        }
        $this->container['jwt_federation_providers'] = $jwt_federation_providers;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


