<?php
/**
 * ProxyProviderRequest
 *
 * PHP version 8.1
 *
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\NextGen\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use AuthentikApi\NextGen\ObjectSerializer;

/**
 * ProxyProviderRequest Class Doc Comment
 *
 * @description ProxyProvider Serializer
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ProxyProviderRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ProxyProviderRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'name' => 'string',
        'authentication_flow' => 'string',
        'authorization_flow' => 'string',
        'invalidation_flow' => 'string',
        'property_mappings' => 'string[]',
        'internal_host' => 'string',
        'external_host' => 'string',
        'internal_host_ssl_validation' => 'bool',
        'certificate' => 'string',
        'skip_path_regex' => 'string',
        'basic_auth_enabled' => 'bool',
        'basic_auth_password_attribute' => 'string',
        'basic_auth_user_attribute' => 'string',
        'mode' => '\AuthentikApi\NextGen\Model\ProxyMode',
        'intercept_header_auth' => 'bool',
        'cookie_domain' => 'string',
        'jwt_federation_sources' => 'string[]',
        'jwt_federation_providers' => 'int[]',
        'access_token_validity' => 'string',
        'refresh_token_validity' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'name' => null,
        'authentication_flow' => 'uuid',
        'authorization_flow' => 'uuid',
        'invalidation_flow' => 'uuid',
        'property_mappings' => 'uuid',
        'internal_host' => 'uri',
        'external_host' => 'uri',
        'internal_host_ssl_validation' => null,
        'certificate' => 'uuid',
        'skip_path_regex' => null,
        'basic_auth_enabled' => null,
        'basic_auth_password_attribute' => null,
        'basic_auth_user_attribute' => null,
        'mode' => null,
        'intercept_header_auth' => null,
        'cookie_domain' => null,
        'jwt_federation_sources' => 'uuid',
        'jwt_federation_providers' => null,
        'access_token_validity' => null,
        'refresh_token_validity' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'name' => false,
        'authentication_flow' => true,
        'authorization_flow' => false,
        'invalidation_flow' => false,
        'property_mappings' => false,
        'internal_host' => false,
        'external_host' => false,
        'internal_host_ssl_validation' => false,
        'certificate' => true,
        'skip_path_regex' => false,
        'basic_auth_enabled' => false,
        'basic_auth_password_attribute' => false,
        'basic_auth_user_attribute' => false,
        'mode' => false,
        'intercept_header_auth' => false,
        'cookie_domain' => false,
        'jwt_federation_sources' => false,
        'jwt_federation_providers' => false,
        'access_token_validity' => false,
        'refresh_token_validity' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'name' => 'name',
        'authentication_flow' => 'authentication_flow',
        'authorization_flow' => 'authorization_flow',
        'invalidation_flow' => 'invalidation_flow',
        'property_mappings' => 'property_mappings',
        'internal_host' => 'internal_host',
        'external_host' => 'external_host',
        'internal_host_ssl_validation' => 'internal_host_ssl_validation',
        'certificate' => 'certificate',
        'skip_path_regex' => 'skip_path_regex',
        'basic_auth_enabled' => 'basic_auth_enabled',
        'basic_auth_password_attribute' => 'basic_auth_password_attribute',
        'basic_auth_user_attribute' => 'basic_auth_user_attribute',
        'mode' => 'mode',
        'intercept_header_auth' => 'intercept_header_auth',
        'cookie_domain' => 'cookie_domain',
        'jwt_federation_sources' => 'jwt_federation_sources',
        'jwt_federation_providers' => 'jwt_federation_providers',
        'access_token_validity' => 'access_token_validity',
        'refresh_token_validity' => 'refresh_token_validity'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'name' => 'setName',
        'authentication_flow' => 'setAuthenticationFlow',
        'authorization_flow' => 'setAuthorizationFlow',
        'invalidation_flow' => 'setInvalidationFlow',
        'property_mappings' => 'setPropertyMappings',
        'internal_host' => 'setInternalHost',
        'external_host' => 'setExternalHost',
        'internal_host_ssl_validation' => 'setInternalHostSslValidation',
        'certificate' => 'setCertificate',
        'skip_path_regex' => 'setSkipPathRegex',
        'basic_auth_enabled' => 'setBasicAuthEnabled',
        'basic_auth_password_attribute' => 'setBasicAuthPasswordAttribute',
        'basic_auth_user_attribute' => 'setBasicAuthUserAttribute',
        'mode' => 'setMode',
        'intercept_header_auth' => 'setInterceptHeaderAuth',
        'cookie_domain' => 'setCookieDomain',
        'jwt_federation_sources' => 'setJwtFederationSources',
        'jwt_federation_providers' => 'setJwtFederationProviders',
        'access_token_validity' => 'setAccessTokenValidity',
        'refresh_token_validity' => 'setRefreshTokenValidity'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'name' => 'getName',
        'authentication_flow' => 'getAuthenticationFlow',
        'authorization_flow' => 'getAuthorizationFlow',
        'invalidation_flow' => 'getInvalidationFlow',
        'property_mappings' => 'getPropertyMappings',
        'internal_host' => 'getInternalHost',
        'external_host' => 'getExternalHost',
        'internal_host_ssl_validation' => 'getInternalHostSslValidation',
        'certificate' => 'getCertificate',
        'skip_path_regex' => 'getSkipPathRegex',
        'basic_auth_enabled' => 'getBasicAuthEnabled',
        'basic_auth_password_attribute' => 'getBasicAuthPasswordAttribute',
        'basic_auth_user_attribute' => 'getBasicAuthUserAttribute',
        'mode' => 'getMode',
        'intercept_header_auth' => 'getInterceptHeaderAuth',
        'cookie_domain' => 'getCookieDomain',
        'jwt_federation_sources' => 'getJwtFederationSources',
        'jwt_federation_providers' => 'getJwtFederationProviders',
        'access_token_validity' => 'getAccessTokenValidity',
        'refresh_token_validity' => 'getRefreshTokenValidity'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('authentication_flow', $data ?? [], null);
        $this->setIfExists('authorization_flow', $data ?? [], null);
        $this->setIfExists('invalidation_flow', $data ?? [], null);
        $this->setIfExists('property_mappings', $data ?? [], null);
        $this->setIfExists('internal_host', $data ?? [], null);
        $this->setIfExists('external_host', $data ?? [], null);
        $this->setIfExists('internal_host_ssl_validation', $data ?? [], null);
        $this->setIfExists('certificate', $data ?? [], null);
        $this->setIfExists('skip_path_regex', $data ?? [], null);
        $this->setIfExists('basic_auth_enabled', $data ?? [], null);
        $this->setIfExists('basic_auth_password_attribute', $data ?? [], null);
        $this->setIfExists('basic_auth_user_attribute', $data ?? [], null);
        $this->setIfExists('mode', $data ?? [], null);
        $this->setIfExists('intercept_header_auth', $data ?? [], null);
        $this->setIfExists('cookie_domain', $data ?? [], null);
        $this->setIfExists('jwt_federation_sources', $data ?? [], null);
        $this->setIfExists('jwt_federation_providers', $data ?? [], null);
        $this->setIfExists('access_token_validity', $data ?? [], null);
        $this->setIfExists('refresh_token_validity', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['authorization_flow'] === null) {
            $invalidProperties[] = "'authorization_flow' can't be null";
        }
        if ($this->container['invalidation_flow'] === null) {
            $invalidProperties[] = "'invalidation_flow' can't be null";
        }
        if ($this->container['external_host'] === null) {
            $invalidProperties[] = "'external_host' can't be null";
        }
        if ((mb_strlen($this->container['external_host']) < 1)) {
            $invalidProperties[] = "invalid value for 'external_host', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['access_token_validity']) && (mb_strlen($this->container['access_token_validity']) < 1)) {
            $invalidProperties[] = "invalid value for 'access_token_validity', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['refresh_token_validity']) && (mb_strlen($this->container['refresh_token_validity']) < 1)) {
            $invalidProperties[] = "invalid value for 'refresh_token_validity', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new InvalidArgumentException('invalid length for $name when calling ProxyProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets authentication_flow
     *
     * @return string|null
     */
    public function getAuthenticationFlow(): ?string
    {
        return $this->container['authentication_flow'];
    }

    /**
     * Sets authentication_flow
     *
     * @param string|null $authentication_flow Flow used for authentication when the associated application is accessed by an un-authenticated user.
     *
     * @return $this
     */
    public function setAuthenticationFlow(?string $authentication_flow): static
    {
        if (is_null($authentication_flow)) {
            array_push($this->openAPINullablesSetToNull, 'authentication_flow');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authentication_flow', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authentication_flow'] = $authentication_flow;

        return $this;
    }

    /**
     * Gets authorization_flow
     *
     * @return string
     */
    public function getAuthorizationFlow(): string
    {
        return $this->container['authorization_flow'];
    }

    /**
     * Sets authorization_flow
     *
     * @param string $authorization_flow Flow used when authorizing this provider.
     *
     * @return $this
     */
    public function setAuthorizationFlow(string $authorization_flow): static
    {
        if (is_null($authorization_flow)) {
            throw new InvalidArgumentException('non-nullable authorization_flow cannot be null');
        }
        $this->container['authorization_flow'] = $authorization_flow;

        return $this;
    }

    /**
     * Gets invalidation_flow
     *
     * @return string
     */
    public function getInvalidationFlow(): string
    {
        return $this->container['invalidation_flow'];
    }

    /**
     * Sets invalidation_flow
     *
     * @param string $invalidation_flow Flow used ending the session from a provider.
     *
     * @return $this
     */
    public function setInvalidationFlow(string $invalidation_flow): static
    {
        if (is_null($invalidation_flow)) {
            throw new InvalidArgumentException('non-nullable invalidation_flow cannot be null');
        }
        $this->container['invalidation_flow'] = $invalidation_flow;

        return $this;
    }

    /**
     * Gets property_mappings
     *
     * @return string[]|null
     */
    public function getPropertyMappings(): ?array
    {
        return $this->container['property_mappings'];
    }

    /**
     * Sets property_mappings
     *
     * @param string[]|null $property_mappings property_mappings
     *
     * @return $this
     */
    public function setPropertyMappings(?array $property_mappings): static
    {
        if (is_null($property_mappings)) {
            throw new InvalidArgumentException('non-nullable property_mappings cannot be null');
        }
        $this->container['property_mappings'] = $property_mappings;

        return $this;
    }

    /**
     * Gets internal_host
     *
     * @return string|null
     */
    public function getInternalHost(): ?string
    {
        return $this->container['internal_host'];
    }

    /**
     * Sets internal_host
     *
     * @param string|null $internal_host internal_host
     *
     * @return $this
     */
    public function setInternalHost(?string $internal_host): static
    {
        if (is_null($internal_host)) {
            throw new InvalidArgumentException('non-nullable internal_host cannot be null');
        }
        $this->container['internal_host'] = $internal_host;

        return $this;
    }

    /**
     * Gets external_host
     *
     * @return string
     */
    public function getExternalHost(): string
    {
        return $this->container['external_host'];
    }

    /**
     * Sets external_host
     *
     * @param string $external_host external_host
     *
     * @return $this
     */
    public function setExternalHost(string $external_host): static
    {
        if (is_null($external_host)) {
            throw new InvalidArgumentException('non-nullable external_host cannot be null');
        }

        if ((mb_strlen($external_host) < 1)) {
            throw new InvalidArgumentException('invalid length for $external_host when calling ProxyProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['external_host'] = $external_host;

        return $this;
    }

    /**
     * Gets internal_host_ssl_validation
     *
     * @return bool|null
     */
    public function getInternalHostSslValidation(): ?bool
    {
        return $this->container['internal_host_ssl_validation'];
    }

    /**
     * Sets internal_host_ssl_validation
     *
     * @param bool|null $internal_host_ssl_validation Validate SSL Certificates of upstream servers
     *
     * @return $this
     */
    public function setInternalHostSslValidation(?bool $internal_host_ssl_validation): static
    {
        if (is_null($internal_host_ssl_validation)) {
            throw new InvalidArgumentException('non-nullable internal_host_ssl_validation cannot be null');
        }
        $this->container['internal_host_ssl_validation'] = $internal_host_ssl_validation;

        return $this;
    }

    /**
     * Gets certificate
     *
     * @return string|null
     */
    public function getCertificate(): ?string
    {
        return $this->container['certificate'];
    }

    /**
     * Sets certificate
     *
     * @param string|null $certificate certificate
     *
     * @return $this
     */
    public function setCertificate(?string $certificate): static
    {
        if (is_null($certificate)) {
            array_push($this->openAPINullablesSetToNull, 'certificate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('certificate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['certificate'] = $certificate;

        return $this;
    }

    /**
     * Gets skip_path_regex
     *
     * @return string|null
     */
    public function getSkipPathRegex(): ?string
    {
        return $this->container['skip_path_regex'];
    }

    /**
     * Sets skip_path_regex
     *
     * @param string|null $skip_path_regex Regular expressions for which authentication is not required. Each new line is interpreted as a new Regular Expression.
     *
     * @return $this
     */
    public function setSkipPathRegex(?string $skip_path_regex): static
    {
        if (is_null($skip_path_regex)) {
            throw new InvalidArgumentException('non-nullable skip_path_regex cannot be null');
        }
        $this->container['skip_path_regex'] = $skip_path_regex;

        return $this;
    }

    /**
     * Gets basic_auth_enabled
     *
     * @return bool|null
     */
    public function getBasicAuthEnabled(): ?bool
    {
        return $this->container['basic_auth_enabled'];
    }

    /**
     * Sets basic_auth_enabled
     *
     * @param bool|null $basic_auth_enabled Set a custom HTTP-Basic Authentication header based on values from authentik.
     *
     * @return $this
     */
    public function setBasicAuthEnabled(?bool $basic_auth_enabled): static
    {
        if (is_null($basic_auth_enabled)) {
            throw new InvalidArgumentException('non-nullable basic_auth_enabled cannot be null');
        }
        $this->container['basic_auth_enabled'] = $basic_auth_enabled;

        return $this;
    }

    /**
     * Gets basic_auth_password_attribute
     *
     * @return string|null
     */
    public function getBasicAuthPasswordAttribute(): ?string
    {
        return $this->container['basic_auth_password_attribute'];
    }

    /**
     * Sets basic_auth_password_attribute
     *
     * @param string|null $basic_auth_password_attribute User/Group Attribute used for the password part of the HTTP-Basic Header.
     *
     * @return $this
     */
    public function setBasicAuthPasswordAttribute(?string $basic_auth_password_attribute): static
    {
        if (is_null($basic_auth_password_attribute)) {
            throw new InvalidArgumentException('non-nullable basic_auth_password_attribute cannot be null');
        }
        $this->container['basic_auth_password_attribute'] = $basic_auth_password_attribute;

        return $this;
    }

    /**
     * Gets basic_auth_user_attribute
     *
     * @return string|null
     */
    public function getBasicAuthUserAttribute(): ?string
    {
        return $this->container['basic_auth_user_attribute'];
    }

    /**
     * Sets basic_auth_user_attribute
     *
     * @param string|null $basic_auth_user_attribute User/Group Attribute used for the user part of the HTTP-Basic Header. If not set, the user's Email address is used.
     *
     * @return $this
     */
    public function setBasicAuthUserAttribute(?string $basic_auth_user_attribute): static
    {
        if (is_null($basic_auth_user_attribute)) {
            throw new InvalidArgumentException('non-nullable basic_auth_user_attribute cannot be null');
        }
        $this->container['basic_auth_user_attribute'] = $basic_auth_user_attribute;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return \AuthentikApi\NextGen\Model\ProxyMode|null
     */
    public function getMode(): ?\AuthentikApi\NextGen\Model\ProxyMode
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param \AuthentikApi\NextGen\Model\ProxyMode|null $mode Enable support for forwardAuth in traefik and nginx auth_request. Exclusive with internal_host.
     *
     * @return $this
     */
    public function setMode(?\AuthentikApi\NextGen\Model\ProxyMode $mode): static
    {
        if (is_null($mode)) {
            throw new InvalidArgumentException('non-nullable mode cannot be null');
        }
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets intercept_header_auth
     *
     * @return bool|null
     */
    public function getInterceptHeaderAuth(): ?bool
    {
        return $this->container['intercept_header_auth'];
    }

    /**
     * Sets intercept_header_auth
     *
     * @param bool|null $intercept_header_auth When enabled, this provider will intercept the authorization header and authenticate requests based on its value.
     *
     * @return $this
     */
    public function setInterceptHeaderAuth(?bool $intercept_header_auth): static
    {
        if (is_null($intercept_header_auth)) {
            throw new InvalidArgumentException('non-nullable intercept_header_auth cannot be null');
        }
        $this->container['intercept_header_auth'] = $intercept_header_auth;

        return $this;
    }

    /**
     * Gets cookie_domain
     *
     * @return string|null
     */
    public function getCookieDomain(): ?string
    {
        return $this->container['cookie_domain'];
    }

    /**
     * Sets cookie_domain
     *
     * @param string|null $cookie_domain cookie_domain
     *
     * @return $this
     */
    public function setCookieDomain(?string $cookie_domain): static
    {
        if (is_null($cookie_domain)) {
            throw new InvalidArgumentException('non-nullable cookie_domain cannot be null');
        }
        $this->container['cookie_domain'] = $cookie_domain;

        return $this;
    }

    /**
     * Gets jwt_federation_sources
     *
     * @return string[]|null
     */
    public function getJwtFederationSources(): ?array
    {
        return $this->container['jwt_federation_sources'];
    }

    /**
     * Sets jwt_federation_sources
     *
     * @param string[]|null $jwt_federation_sources jwt_federation_sources
     *
     * @return $this
     */
    public function setJwtFederationSources(?array $jwt_federation_sources): static
    {
        if (is_null($jwt_federation_sources)) {
            throw new InvalidArgumentException('non-nullable jwt_federation_sources cannot be null');
        }
        $this->container['jwt_federation_sources'] = $jwt_federation_sources;

        return $this;
    }

    /**
     * Gets jwt_federation_providers
     *
     * @return int[]|null
     */
    public function getJwtFederationProviders(): ?array
    {
        return $this->container['jwt_federation_providers'];
    }

    /**
     * Sets jwt_federation_providers
     *
     * @param int[]|null $jwt_federation_providers jwt_federation_providers
     *
     * @return $this
     */
    public function setJwtFederationProviders(?array $jwt_federation_providers): static
    {
        if (is_null($jwt_federation_providers)) {
            throw new InvalidArgumentException('non-nullable jwt_federation_providers cannot be null');
        }
        $this->container['jwt_federation_providers'] = $jwt_federation_providers;

        return $this;
    }

    /**
     * Gets access_token_validity
     *
     * @return string|null
     */
    public function getAccessTokenValidity(): ?string
    {
        return $this->container['access_token_validity'];
    }

    /**
     * Sets access_token_validity
     *
     * @param string|null $access_token_validity Tokens not valid on or after current time + this value (Format: hours=1;minutes=2;seconds=3).
     *
     * @return $this
     */
    public function setAccessTokenValidity(?string $access_token_validity): static
    {
        if (is_null($access_token_validity)) {
            throw new InvalidArgumentException('non-nullable access_token_validity cannot be null');
        }

        if ((mb_strlen($access_token_validity) < 1)) {
            throw new InvalidArgumentException('invalid length for $access_token_validity when calling ProxyProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['access_token_validity'] = $access_token_validity;

        return $this;
    }

    /**
     * Gets refresh_token_validity
     *
     * @return string|null
     */
    public function getRefreshTokenValidity(): ?string
    {
        return $this->container['refresh_token_validity'];
    }

    /**
     * Sets refresh_token_validity
     *
     * @param string|null $refresh_token_validity Tokens not valid on or after current time + this value (Format: hours=1;minutes=2;seconds=3).
     *
     * @return $this
     */
    public function setRefreshTokenValidity(?string $refresh_token_validity): static
    {
        if (is_null($refresh_token_validity)) {
            throw new InvalidArgumentException('non-nullable refresh_token_validity cannot be null');
        }

        if ((mb_strlen($refresh_token_validity) < 1)) {
            throw new InvalidArgumentException('invalid length for $refresh_token_validity when calling ProxyProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['refresh_token_validity'] = $refresh_token_validity;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


