<?php
/**
 * RadiusProviderRequest
 *
 * PHP version 8.1
 *
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\NextGen\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use AuthentikApi\NextGen\ObjectSerializer;

/**
 * RadiusProviderRequest Class Doc Comment
 *
 * @description RadiusProvider Serializer
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class RadiusProviderRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'RadiusProviderRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'name' => 'string',
        'authentication_flow' => 'string',
        'authorization_flow' => 'string',
        'invalidation_flow' => 'string',
        'property_mappings' => 'string[]',
        'client_networks' => 'string',
        'shared_secret' => 'string',
        'mfa_support' => 'bool',
        'certificate' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'name' => null,
        'authentication_flow' => 'uuid',
        'authorization_flow' => 'uuid',
        'invalidation_flow' => 'uuid',
        'property_mappings' => 'uuid',
        'client_networks' => null,
        'shared_secret' => null,
        'mfa_support' => null,
        'certificate' => 'uuid'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'name' => false,
        'authentication_flow' => true,
        'authorization_flow' => false,
        'invalidation_flow' => false,
        'property_mappings' => false,
        'client_networks' => false,
        'shared_secret' => false,
        'mfa_support' => false,
        'certificate' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'name' => 'name',
        'authentication_flow' => 'authentication_flow',
        'authorization_flow' => 'authorization_flow',
        'invalidation_flow' => 'invalidation_flow',
        'property_mappings' => 'property_mappings',
        'client_networks' => 'client_networks',
        'shared_secret' => 'shared_secret',
        'mfa_support' => 'mfa_support',
        'certificate' => 'certificate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'name' => 'setName',
        'authentication_flow' => 'setAuthenticationFlow',
        'authorization_flow' => 'setAuthorizationFlow',
        'invalidation_flow' => 'setInvalidationFlow',
        'property_mappings' => 'setPropertyMappings',
        'client_networks' => 'setClientNetworks',
        'shared_secret' => 'setSharedSecret',
        'mfa_support' => 'setMfaSupport',
        'certificate' => 'setCertificate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'name' => 'getName',
        'authentication_flow' => 'getAuthenticationFlow',
        'authorization_flow' => 'getAuthorizationFlow',
        'invalidation_flow' => 'getInvalidationFlow',
        'property_mappings' => 'getPropertyMappings',
        'client_networks' => 'getClientNetworks',
        'shared_secret' => 'getSharedSecret',
        'mfa_support' => 'getMfaSupport',
        'certificate' => 'getCertificate'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('authentication_flow', $data ?? [], null);
        $this->setIfExists('authorization_flow', $data ?? [], null);
        $this->setIfExists('invalidation_flow', $data ?? [], null);
        $this->setIfExists('property_mappings', $data ?? [], null);
        $this->setIfExists('client_networks', $data ?? [], null);
        $this->setIfExists('shared_secret', $data ?? [], null);
        $this->setIfExists('mfa_support', $data ?? [], null);
        $this->setIfExists('certificate', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['authorization_flow'] === null) {
            $invalidProperties[] = "'authorization_flow' can't be null";
        }
        if ($this->container['invalidation_flow'] === null) {
            $invalidProperties[] = "'invalidation_flow' can't be null";
        }
        if (!is_null($this->container['client_networks']) && (mb_strlen($this->container['client_networks']) < 1)) {
            $invalidProperties[] = "invalid value for 'client_networks', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['shared_secret']) && (mb_strlen($this->container['shared_secret']) < 1)) {
            $invalidProperties[] = "invalid value for 'shared_secret', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new InvalidArgumentException('invalid length for $name when calling RadiusProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets authentication_flow
     *
     * @return string|null
     */
    public function getAuthenticationFlow(): ?string
    {
        return $this->container['authentication_flow'];
    }

    /**
     * Sets authentication_flow
     *
     * @param string|null $authentication_flow Flow used for authentication when the associated application is accessed by an un-authenticated user.
     *
     * @return $this
     */
    public function setAuthenticationFlow(?string $authentication_flow): static
    {
        if (is_null($authentication_flow)) {
            array_push($this->openAPINullablesSetToNull, 'authentication_flow');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authentication_flow', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authentication_flow'] = $authentication_flow;

        return $this;
    }

    /**
     * Gets authorization_flow
     *
     * @return string
     */
    public function getAuthorizationFlow(): string
    {
        return $this->container['authorization_flow'];
    }

    /**
     * Sets authorization_flow
     *
     * @param string $authorization_flow Flow used when authorizing this provider.
     *
     * @return $this
     */
    public function setAuthorizationFlow(string $authorization_flow): static
    {
        if (is_null($authorization_flow)) {
            throw new InvalidArgumentException('non-nullable authorization_flow cannot be null');
        }
        $this->container['authorization_flow'] = $authorization_flow;

        return $this;
    }

    /**
     * Gets invalidation_flow
     *
     * @return string
     */
    public function getInvalidationFlow(): string
    {
        return $this->container['invalidation_flow'];
    }

    /**
     * Sets invalidation_flow
     *
     * @param string $invalidation_flow Flow used ending the session from a provider.
     *
     * @return $this
     */
    public function setInvalidationFlow(string $invalidation_flow): static
    {
        if (is_null($invalidation_flow)) {
            throw new InvalidArgumentException('non-nullable invalidation_flow cannot be null');
        }
        $this->container['invalidation_flow'] = $invalidation_flow;

        return $this;
    }

    /**
     * Gets property_mappings
     *
     * @return string[]|null
     */
    public function getPropertyMappings(): ?array
    {
        return $this->container['property_mappings'];
    }

    /**
     * Sets property_mappings
     *
     * @param string[]|null $property_mappings property_mappings
     *
     * @return $this
     */
    public function setPropertyMappings(?array $property_mappings): static
    {
        if (is_null($property_mappings)) {
            throw new InvalidArgumentException('non-nullable property_mappings cannot be null');
        }
        $this->container['property_mappings'] = $property_mappings;

        return $this;
    }

    /**
     * Gets client_networks
     *
     * @return string|null
     */
    public function getClientNetworks(): ?string
    {
        return $this->container['client_networks'];
    }

    /**
     * Sets client_networks
     *
     * @param string|null $client_networks List of CIDRs (comma-separated) that clients can connect from. A more specific CIDR will match before a looser one. Clients connecting from a non-specified CIDR will be dropped.
     *
     * @return $this
     */
    public function setClientNetworks(?string $client_networks): static
    {
        if (is_null($client_networks)) {
            throw new InvalidArgumentException('non-nullable client_networks cannot be null');
        }

        if ((mb_strlen($client_networks) < 1)) {
            throw new InvalidArgumentException('invalid length for $client_networks when calling RadiusProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['client_networks'] = $client_networks;

        return $this;
    }

    /**
     * Gets shared_secret
     *
     * @return string|null
     */
    public function getSharedSecret(): ?string
    {
        return $this->container['shared_secret'];
    }

    /**
     * Sets shared_secret
     *
     * @param string|null $shared_secret Shared secret between clients and server to hash packets.
     *
     * @return $this
     */
    public function setSharedSecret(?string $shared_secret): static
    {
        if (is_null($shared_secret)) {
            throw new InvalidArgumentException('non-nullable shared_secret cannot be null');
        }

        if ((mb_strlen($shared_secret) < 1)) {
            throw new InvalidArgumentException('invalid length for $shared_secret when calling RadiusProviderRequest., must be bigger than or equal to 1.');
        }

        $this->container['shared_secret'] = $shared_secret;

        return $this;
    }

    /**
     * Gets mfa_support
     *
     * @return bool|null
     */
    public function getMfaSupport(): ?bool
    {
        return $this->container['mfa_support'];
    }

    /**
     * Sets mfa_support
     *
     * @param bool|null $mfa_support When enabled, code-based multi-factor authentication can be used by appending a semicolon and the TOTP code to the password. This should only be enabled if all users that will bind to this provider have a TOTP device configured, as otherwise a password may incorrectly be rejected if it contains a semicolon.
     *
     * @return $this
     */
    public function setMfaSupport(?bool $mfa_support): static
    {
        if (is_null($mfa_support)) {
            throw new InvalidArgumentException('non-nullable mfa_support cannot be null');
        }
        $this->container['mfa_support'] = $mfa_support;

        return $this;
    }

    /**
     * Gets certificate
     *
     * @return string|null
     */
    public function getCertificate(): ?string
    {
        return $this->container['certificate'];
    }

    /**
     * Sets certificate
     *
     * @param string|null $certificate certificate
     *
     * @return $this
     */
    public function setCertificate(?string $certificate): static
    {
        if (is_null($certificate)) {
            array_push($this->openAPINullablesSetToNull, 'certificate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('certificate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['certificate'] = $certificate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


