<?php
/**
 * SubModeEnum
 *
 * PHP version 8.1
 *
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\NextGen\Model;

/**
 * SubModeEnum Class Doc Comment
 *
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum SubModeEnum: string
{
    case HASHED_USER_ID = 'hashed_user_id';

    case USER_ID = 'user_id';

    case USER_UUID = 'user_uuid';

    case USER_USERNAME = 'user_username';

    case USER_EMAIL = 'user_email';

    case USER_UPN = 'user_upn';
}


