<?php
/**
 * UsedByActionEnum
 *
 * PHP version 8.1
 *
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * authentik
 *
 * Excerpt of the authentik openapi docs
 *
 * The version of the OpenAPI document: 2026.2.3
 * Contact: hello@goauthentik.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AuthentikApi\NextGen\Model;

/**
 * UsedByActionEnum Class Doc Comment
 *
 * @package  AuthentikApi\NextGen
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum UsedByActionEnum: string
{
    case CASCADE = 'cascade';

    case CASCADE_MANY = 'cascade_many';

    case SET_NULL = 'set_null';

    case SET_DEFAULT = 'set_default';

    case LEFT_DANGLING = 'left_dangling';
}


